package test.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   General log
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table general_log
 */
public class GeneralLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_log.event_time
     *
     * @mbg.generated
     */
    private Date eventTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_log.thread_id
     *
     * @mbg.generated
     */
    private Long threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_log.server_id
     *
     * @mbg.generated
     */
    private Integer serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_log.command_type
     *
     * @mbg.generated
     */
    private String commandType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_log.user_host
     *
     * @mbg.generated
     */
    private String userHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_log.argument
     *
     * @mbg.generated
     */
    private byte[] argument;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_log.event_time
     *
     * @return the value of general_log.event_time
     *
     * @mbg.generated
     */
    public Date getEventTime() {
        return eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_log.event_time
     *
     * @param eventTime the value for general_log.event_time
     *
     * @mbg.generated
     */
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_log.thread_id
     *
     * @return the value of general_log.thread_id
     *
     * @mbg.generated
     */
    public Long getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_log.thread_id
     *
     * @param threadId the value for general_log.thread_id
     *
     * @mbg.generated
     */
    public void setThreadId(Long threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_log.server_id
     *
     * @return the value of general_log.server_id
     *
     * @mbg.generated
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_log.server_id
     *
     * @param serverId the value for general_log.server_id
     *
     * @mbg.generated
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_log.command_type
     *
     * @return the value of general_log.command_type
     *
     * @mbg.generated
     */
    public String getCommandType() {
        return commandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_log.command_type
     *
     * @param commandType the value for general_log.command_type
     *
     * @mbg.generated
     */
    public void setCommandType(String commandType) {
        this.commandType = commandType == null ? null : commandType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_log.user_host
     *
     * @return the value of general_log.user_host
     *
     * @mbg.generated
     */
    public String getUserHost() {
        return userHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_log.user_host
     *
     * @param userHost the value for general_log.user_host
     *
     * @mbg.generated
     */
    public void setUserHost(String userHost) {
        this.userHost = userHost == null ? null : userHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_log.argument
     *
     * @return the value of general_log.argument
     *
     * @mbg.generated
     */
    public byte[] getArgument() {
        return argument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_log.argument
     *
     * @param argument the value for general_log.argument
     *
     * @mbg.generated
     */
    public void setArgument(byte[] argument) {
        this.argument = argument;
    }
}