package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table global_status
 */
public class GlobalStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_status.VARIABLE_NAME
     *
     * @mbg.generated
     */
    private String variableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_status.VARIABLE_VALUE
     *
     * @mbg.generated
     */
    private String variableValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_status.VARIABLE_NAME
     *
     * @return the value of global_status.VARIABLE_NAME
     *
     * @mbg.generated
     */
    public String getVariableName() {
        return variableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_status.VARIABLE_NAME
     *
     * @param variableName the value for global_status.VARIABLE_NAME
     *
     * @mbg.generated
     */
    public void setVariableName(String variableName) {
        this.variableName = variableName == null ? null : variableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_status.VARIABLE_VALUE
     *
     * @return the value of global_status.VARIABLE_VALUE
     *
     * @mbg.generated
     */
    public String getVariableValue() {
        return variableValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_status.VARIABLE_VALUE
     *
     * @param variableValue the value for global_status.VARIABLE_VALUE
     *
     * @mbg.generated
     */
    public void setVariableValue(String variableValue) {
        this.variableValue = variableValue == null ? null : variableValue.trim();
    }
}