package test.model;

/**
 * Database Table Remarks:
 *   Extended global grants
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table global_grants
 */
public class GlobalGrants {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_grants.USER
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_grants.HOST
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_grants.PRIV
     *
     * @mbg.generated
     */
    private String priv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_grants.WITH_GRANT_OPTION
     *
     * @mbg.generated
     */
    private String withGrantOption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_grants.USER
     *
     * @return the value of global_grants.USER
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_grants.USER
     *
     * @param user the value for global_grants.USER
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_grants.HOST
     *
     * @return the value of global_grants.HOST
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_grants.HOST
     *
     * @param host the value for global_grants.HOST
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_grants.PRIV
     *
     * @return the value of global_grants.PRIV
     *
     * @mbg.generated
     */
    public String getPriv() {
        return priv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_grants.PRIV
     *
     * @param priv the value for global_grants.PRIV
     *
     * @mbg.generated
     */
    public void setPriv(String priv) {
        this.priv = priv == null ? null : priv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_grants.WITH_GRANT_OPTION
     *
     * @return the value of global_grants.WITH_GRANT_OPTION
     *
     * @mbg.generated
     */
    public String getWithGrantOption() {
        return withGrantOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_grants.WITH_GRANT_OPTION
     *
     * @param withGrantOption the value for global_grants.WITH_GRANT_OPTION
     *
     * @mbg.generated
     */
    public void setWithGrantOption(String withGrantOption) {
        this.withGrantOption = withGrantOption == null ? null : withGrantOption.trim();
    }
}