package test.model;

/**
 * Database Table Remarks:
 *   help topics
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table help_topic
 */
public class HelpTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_topic.help_topic_id
     *
     * @mbg.generated
     */
    private Integer helpTopicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_topic.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_topic.help_category_id
     *
     * @mbg.generated
     */
    private Short helpCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_topic.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_topic.example
     *
     * @mbg.generated
     */
    private String example;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_topic.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_topic.help_topic_id
     *
     * @return the value of help_topic.help_topic_id
     *
     * @mbg.generated
     */
    public Integer getHelpTopicId() {
        return helpTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_topic.help_topic_id
     *
     * @param helpTopicId the value for help_topic.help_topic_id
     *
     * @mbg.generated
     */
    public void setHelpTopicId(Integer helpTopicId) {
        this.helpTopicId = helpTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_topic.name
     *
     * @return the value of help_topic.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_topic.name
     *
     * @param name the value for help_topic.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_topic.help_category_id
     *
     * @return the value of help_topic.help_category_id
     *
     * @mbg.generated
     */
    public Short getHelpCategoryId() {
        return helpCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_topic.help_category_id
     *
     * @param helpCategoryId the value for help_topic.help_category_id
     *
     * @mbg.generated
     */
    public void setHelpCategoryId(Short helpCategoryId) {
        this.helpCategoryId = helpCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_topic.description
     *
     * @return the value of help_topic.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_topic.description
     *
     * @param description the value for help_topic.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_topic.example
     *
     * @return the value of help_topic.example
     *
     * @mbg.generated
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_topic.example
     *
     * @param example the value for help_topic.example
     *
     * @mbg.generated
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_topic.url
     *
     * @return the value of help_topic.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_topic.url
     *
     * @param url the value for help_topic.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}