package test.model;

/**
 * Database Table Remarks:
 *   help categories
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table help_category
 */
public class HelpCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.help_category_id
     *
     * @mbg.generated
     */
    private Short helpCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.parent_category_id
     *
     * @mbg.generated
     */
    private Short parentCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column help_category.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.help_category_id
     *
     * @return the value of help_category.help_category_id
     *
     * @mbg.generated
     */
    public Short getHelpCategoryId() {
        return helpCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.help_category_id
     *
     * @param helpCategoryId the value for help_category.help_category_id
     *
     * @mbg.generated
     */
    public void setHelpCategoryId(Short helpCategoryId) {
        this.helpCategoryId = helpCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.name
     *
     * @return the value of help_category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.name
     *
     * @param name the value for help_category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.parent_category_id
     *
     * @return the value of help_category.parent_category_id
     *
     * @mbg.generated
     */
    public Short getParentCategoryId() {
        return parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.parent_category_id
     *
     * @param parentCategoryId the value for help_category.parent_category_id
     *
     * @mbg.generated
     */
    public void setParentCategoryId(Short parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column help_category.url
     *
     * @return the value of help_category.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column help_category.url
     *
     * @param url the value for help_category.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}