package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table host_summary_by_file_io_type
 */
public class HostSummaryByFileIoType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary_by_file_io_type.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary_by_file_io_type.event_name
     *
     * @mbg.generated
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary_by_file_io_type.total
     *
     * @mbg.generated
     */
    private Long total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary_by_file_io_type.total_latency
     *
     * @mbg.generated
     */
    private String totalLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary_by_file_io_type.max_latency
     *
     * @mbg.generated
     */
    private String maxLatency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary_by_file_io_type.host
     *
     * @return the value of host_summary_by_file_io_type.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary_by_file_io_type.host
     *
     * @param host the value for host_summary_by_file_io_type.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary_by_file_io_type.event_name
     *
     * @return the value of host_summary_by_file_io_type.event_name
     *
     * @mbg.generated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary_by_file_io_type.event_name
     *
     * @param eventName the value for host_summary_by_file_io_type.event_name
     *
     * @mbg.generated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary_by_file_io_type.total
     *
     * @return the value of host_summary_by_file_io_type.total
     *
     * @mbg.generated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary_by_file_io_type.total
     *
     * @param total the value for host_summary_by_file_io_type.total
     *
     * @mbg.generated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary_by_file_io_type.total_latency
     *
     * @return the value of host_summary_by_file_io_type.total_latency
     *
     * @mbg.generated
     */
    public String getTotalLatency() {
        return totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary_by_file_io_type.total_latency
     *
     * @param totalLatency the value for host_summary_by_file_io_type.total_latency
     *
     * @mbg.generated
     */
    public void setTotalLatency(String totalLatency) {
        this.totalLatency = totalLatency == null ? null : totalLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary_by_file_io_type.max_latency
     *
     * @return the value of host_summary_by_file_io_type.max_latency
     *
     * @mbg.generated
     */
    public String getMaxLatency() {
        return maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary_by_file_io_type.max_latency
     *
     * @param maxLatency the value for host_summary_by_file_io_type.max_latency
     *
     * @mbg.generated
     */
    public void setMaxLatency(String maxLatency) {
        this.maxLatency = maxLatency == null ? null : maxLatency.trim();
    }
}