package test.model;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table host_summary
 */
public class HostSummary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.statements
     *
     * @mbg.generated
     */
    private BigDecimal statements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.table_scans
     *
     * @mbg.generated
     */
    private BigDecimal tableScans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.file_ios
     *
     * @mbg.generated
     */
    private BigDecimal fileIos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.current_connections
     *
     * @mbg.generated
     */
    private BigDecimal currentConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.total_connections
     *
     * @mbg.generated
     */
    private BigDecimal totalConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.unique_users
     *
     * @mbg.generated
     */
    private Long uniqueUsers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.statement_latency
     *
     * @mbg.generated
     */
    private String statementLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.statement_avg_latency
     *
     * @mbg.generated
     */
    private String statementAvgLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.file_io_latency
     *
     * @mbg.generated
     */
    private String fileIoLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.current_memory
     *
     * @mbg.generated
     */
    private String currentMemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_summary.total_memory_allocated
     *
     * @mbg.generated
     */
    private String totalMemoryAllocated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.host
     *
     * @return the value of host_summary.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.host
     *
     * @param host the value for host_summary.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.statements
     *
     * @return the value of host_summary.statements
     *
     * @mbg.generated
     */
    public BigDecimal getStatements() {
        return statements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.statements
     *
     * @param statements the value for host_summary.statements
     *
     * @mbg.generated
     */
    public void setStatements(BigDecimal statements) {
        this.statements = statements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.table_scans
     *
     * @return the value of host_summary.table_scans
     *
     * @mbg.generated
     */
    public BigDecimal getTableScans() {
        return tableScans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.table_scans
     *
     * @param tableScans the value for host_summary.table_scans
     *
     * @mbg.generated
     */
    public void setTableScans(BigDecimal tableScans) {
        this.tableScans = tableScans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.file_ios
     *
     * @return the value of host_summary.file_ios
     *
     * @mbg.generated
     */
    public BigDecimal getFileIos() {
        return fileIos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.file_ios
     *
     * @param fileIos the value for host_summary.file_ios
     *
     * @mbg.generated
     */
    public void setFileIos(BigDecimal fileIos) {
        this.fileIos = fileIos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.current_connections
     *
     * @return the value of host_summary.current_connections
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentConnections() {
        return currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.current_connections
     *
     * @param currentConnections the value for host_summary.current_connections
     *
     * @mbg.generated
     */
    public void setCurrentConnections(BigDecimal currentConnections) {
        this.currentConnections = currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.total_connections
     *
     * @return the value of host_summary.total_connections
     *
     * @mbg.generated
     */
    public BigDecimal getTotalConnections() {
        return totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.total_connections
     *
     * @param totalConnections the value for host_summary.total_connections
     *
     * @mbg.generated
     */
    public void setTotalConnections(BigDecimal totalConnections) {
        this.totalConnections = totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.unique_users
     *
     * @return the value of host_summary.unique_users
     *
     * @mbg.generated
     */
    public Long getUniqueUsers() {
        return uniqueUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.unique_users
     *
     * @param uniqueUsers the value for host_summary.unique_users
     *
     * @mbg.generated
     */
    public void setUniqueUsers(Long uniqueUsers) {
        this.uniqueUsers = uniqueUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.statement_latency
     *
     * @return the value of host_summary.statement_latency
     *
     * @mbg.generated
     */
    public String getStatementLatency() {
        return statementLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.statement_latency
     *
     * @param statementLatency the value for host_summary.statement_latency
     *
     * @mbg.generated
     */
    public void setStatementLatency(String statementLatency) {
        this.statementLatency = statementLatency == null ? null : statementLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.statement_avg_latency
     *
     * @return the value of host_summary.statement_avg_latency
     *
     * @mbg.generated
     */
    public String getStatementAvgLatency() {
        return statementAvgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.statement_avg_latency
     *
     * @param statementAvgLatency the value for host_summary.statement_avg_latency
     *
     * @mbg.generated
     */
    public void setStatementAvgLatency(String statementAvgLatency) {
        this.statementAvgLatency = statementAvgLatency == null ? null : statementAvgLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.file_io_latency
     *
     * @return the value of host_summary.file_io_latency
     *
     * @mbg.generated
     */
    public String getFileIoLatency() {
        return fileIoLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.file_io_latency
     *
     * @param fileIoLatency the value for host_summary.file_io_latency
     *
     * @mbg.generated
     */
    public void setFileIoLatency(String fileIoLatency) {
        this.fileIoLatency = fileIoLatency == null ? null : fileIoLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.current_memory
     *
     * @return the value of host_summary.current_memory
     *
     * @mbg.generated
     */
    public String getCurrentMemory() {
        return currentMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.current_memory
     *
     * @param currentMemory the value for host_summary.current_memory
     *
     * @mbg.generated
     */
    public void setCurrentMemory(String currentMemory) {
        this.currentMemory = currentMemory == null ? null : currentMemory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_summary.total_memory_allocated
     *
     * @return the value of host_summary.total_memory_allocated
     *
     * @mbg.generated
     */
    public String getTotalMemoryAllocated() {
        return totalMemoryAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_summary.total_memory_allocated
     *
     * @param totalMemoryAllocated the value for host_summary.total_memory_allocated
     *
     * @mbg.generated
     */
    public void setTotalMemoryAllocated(String totalMemoryAllocated) {
        this.totalMemoryAllocated = totalMemoryAllocated == null ? null : totalMemoryAllocated.trim();
    }
}