package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table INNODB_CMP_PER_INDEX
 */
public class InnodbCmpPerIndex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.database_name
     *
     * @mbg.generated
     */
    private String databaseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.index_name
     *
     * @mbg.generated
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.compress_ops
     *
     * @mbg.generated
     */
    private Integer compressOps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.compress_ops_ok
     *
     * @mbg.generated
     */
    private Integer compressOpsOk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.compress_time
     *
     * @mbg.generated
     */
    private Integer compressTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.uncompress_ops
     *
     * @mbg.generated
     */
    private Integer uncompressOps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_CMP_PER_INDEX.uncompress_time
     *
     * @mbg.generated
     */
    private Integer uncompressTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.database_name
     *
     * @return the value of INNODB_CMP_PER_INDEX.database_name
     *
     * @mbg.generated
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.database_name
     *
     * @param databaseName the value for INNODB_CMP_PER_INDEX.database_name
     *
     * @mbg.generated
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName == null ? null : databaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.table_name
     *
     * @return the value of INNODB_CMP_PER_INDEX.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.table_name
     *
     * @param tableName the value for INNODB_CMP_PER_INDEX.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.index_name
     *
     * @return the value of INNODB_CMP_PER_INDEX.index_name
     *
     * @mbg.generated
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.index_name
     *
     * @param indexName the value for INNODB_CMP_PER_INDEX.index_name
     *
     * @mbg.generated
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.compress_ops
     *
     * @return the value of INNODB_CMP_PER_INDEX.compress_ops
     *
     * @mbg.generated
     */
    public Integer getCompressOps() {
        return compressOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.compress_ops
     *
     * @param compressOps the value for INNODB_CMP_PER_INDEX.compress_ops
     *
     * @mbg.generated
     */
    public void setCompressOps(Integer compressOps) {
        this.compressOps = compressOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.compress_ops_ok
     *
     * @return the value of INNODB_CMP_PER_INDEX.compress_ops_ok
     *
     * @mbg.generated
     */
    public Integer getCompressOpsOk() {
        return compressOpsOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.compress_ops_ok
     *
     * @param compressOpsOk the value for INNODB_CMP_PER_INDEX.compress_ops_ok
     *
     * @mbg.generated
     */
    public void setCompressOpsOk(Integer compressOpsOk) {
        this.compressOpsOk = compressOpsOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.compress_time
     *
     * @return the value of INNODB_CMP_PER_INDEX.compress_time
     *
     * @mbg.generated
     */
    public Integer getCompressTime() {
        return compressTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.compress_time
     *
     * @param compressTime the value for INNODB_CMP_PER_INDEX.compress_time
     *
     * @mbg.generated
     */
    public void setCompressTime(Integer compressTime) {
        this.compressTime = compressTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.uncompress_ops
     *
     * @return the value of INNODB_CMP_PER_INDEX.uncompress_ops
     *
     * @mbg.generated
     */
    public Integer getUncompressOps() {
        return uncompressOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.uncompress_ops
     *
     * @param uncompressOps the value for INNODB_CMP_PER_INDEX.uncompress_ops
     *
     * @mbg.generated
     */
    public void setUncompressOps(Integer uncompressOps) {
        this.uncompressOps = uncompressOps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_CMP_PER_INDEX.uncompress_time
     *
     * @return the value of INNODB_CMP_PER_INDEX.uncompress_time
     *
     * @mbg.generated
     */
    public Integer getUncompressTime() {
        return uncompressTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_CMP_PER_INDEX.uncompress_time
     *
     * @param uncompressTime the value for INNODB_CMP_PER_INDEX.uncompress_time
     *
     * @mbg.generated
     */
    public void setUncompressTime(Integer uncompressTime) {
        this.uncompressTime = uncompressTime;
    }
}