package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table INNODB_TABLESPACES
 */
public class InnodbTablespaces {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.SPACE
     *
     * @mbg.generated
     */
    private Integer space;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.FLAG
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.ROW_FORMAT
     *
     * @mbg.generated
     */
    private String rowFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.PAGE_SIZE
     *
     * @mbg.generated
     */
    private Integer pageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @mbg.generated
     */
    private Integer zipPageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.SPACE_TYPE
     *
     * @mbg.generated
     */
    private String spaceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.FS_BLOCK_SIZE
     *
     * @mbg.generated
     */
    private Integer fsBlockSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.FILE_SIZE
     *
     * @mbg.generated
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.ALLOCATED_SIZE
     *
     * @mbg.generated
     */
    private Long allocatedSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.SERVER_VERSION
     *
     * @mbg.generated
     */
    private String serverVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.SPACE_VERSION
     *
     * @mbg.generated
     */
    private Integer spaceVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_TABLESPACES.ENCRYPTION
     *
     * @mbg.generated
     */
    private String encryption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.SPACE
     *
     * @return the value of INNODB_TABLESPACES.SPACE
     *
     * @mbg.generated
     */
    public Integer getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.SPACE
     *
     * @param space the value for INNODB_TABLESPACES.SPACE
     *
     * @mbg.generated
     */
    public void setSpace(Integer space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.NAME
     *
     * @return the value of INNODB_TABLESPACES.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.NAME
     *
     * @param name the value for INNODB_TABLESPACES.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.FLAG
     *
     * @return the value of INNODB_TABLESPACES.FLAG
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.FLAG
     *
     * @param flag the value for INNODB_TABLESPACES.FLAG
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.ROW_FORMAT
     *
     * @return the value of INNODB_TABLESPACES.ROW_FORMAT
     *
     * @mbg.generated
     */
    public String getRowFormat() {
        return rowFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.ROW_FORMAT
     *
     * @param rowFormat the value for INNODB_TABLESPACES.ROW_FORMAT
     *
     * @mbg.generated
     */
    public void setRowFormat(String rowFormat) {
        this.rowFormat = rowFormat == null ? null : rowFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.PAGE_SIZE
     *
     * @return the value of INNODB_TABLESPACES.PAGE_SIZE
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.PAGE_SIZE
     *
     * @param pageSize the value for INNODB_TABLESPACES.PAGE_SIZE
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @return the value of INNODB_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @mbg.generated
     */
    public Integer getZipPageSize() {
        return zipPageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @param zipPageSize the value for INNODB_TABLESPACES.ZIP_PAGE_SIZE
     *
     * @mbg.generated
     */
    public void setZipPageSize(Integer zipPageSize) {
        this.zipPageSize = zipPageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.SPACE_TYPE
     *
     * @return the value of INNODB_TABLESPACES.SPACE_TYPE
     *
     * @mbg.generated
     */
    public String getSpaceType() {
        return spaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.SPACE_TYPE
     *
     * @param spaceType the value for INNODB_TABLESPACES.SPACE_TYPE
     *
     * @mbg.generated
     */
    public void setSpaceType(String spaceType) {
        this.spaceType = spaceType == null ? null : spaceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.FS_BLOCK_SIZE
     *
     * @return the value of INNODB_TABLESPACES.FS_BLOCK_SIZE
     *
     * @mbg.generated
     */
    public Integer getFsBlockSize() {
        return fsBlockSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.FS_BLOCK_SIZE
     *
     * @param fsBlockSize the value for INNODB_TABLESPACES.FS_BLOCK_SIZE
     *
     * @mbg.generated
     */
    public void setFsBlockSize(Integer fsBlockSize) {
        this.fsBlockSize = fsBlockSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.FILE_SIZE
     *
     * @return the value of INNODB_TABLESPACES.FILE_SIZE
     *
     * @mbg.generated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.FILE_SIZE
     *
     * @param fileSize the value for INNODB_TABLESPACES.FILE_SIZE
     *
     * @mbg.generated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.ALLOCATED_SIZE
     *
     * @return the value of INNODB_TABLESPACES.ALLOCATED_SIZE
     *
     * @mbg.generated
     */
    public Long getAllocatedSize() {
        return allocatedSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.ALLOCATED_SIZE
     *
     * @param allocatedSize the value for INNODB_TABLESPACES.ALLOCATED_SIZE
     *
     * @mbg.generated
     */
    public void setAllocatedSize(Long allocatedSize) {
        this.allocatedSize = allocatedSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.SERVER_VERSION
     *
     * @return the value of INNODB_TABLESPACES.SERVER_VERSION
     *
     * @mbg.generated
     */
    public String getServerVersion() {
        return serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.SERVER_VERSION
     *
     * @param serverVersion the value for INNODB_TABLESPACES.SERVER_VERSION
     *
     * @mbg.generated
     */
    public void setServerVersion(String serverVersion) {
        this.serverVersion = serverVersion == null ? null : serverVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.SPACE_VERSION
     *
     * @return the value of INNODB_TABLESPACES.SPACE_VERSION
     *
     * @mbg.generated
     */
    public Integer getSpaceVersion() {
        return spaceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.SPACE_VERSION
     *
     * @param spaceVersion the value for INNODB_TABLESPACES.SPACE_VERSION
     *
     * @mbg.generated
     */
    public void setSpaceVersion(Integer spaceVersion) {
        this.spaceVersion = spaceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_TABLESPACES.ENCRYPTION
     *
     * @return the value of INNODB_TABLESPACES.ENCRYPTION
     *
     * @mbg.generated
     */
    public String getEncryption() {
        return encryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_TABLESPACES.ENCRYPTION
     *
     * @param encryption the value for INNODB_TABLESPACES.ENCRYPTION
     *
     * @mbg.generated
     */
    public void setEncryption(String encryption) {
        this.encryption = encryption == null ? null : encryption.trim();
    }
}