package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table io_global_by_wait_by_latency
 */
public class IoGlobalByWaitByLatency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.event_name
     *
     * @mbg.generated
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.total
     *
     * @mbg.generated
     */
    private Long total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.count_read
     *
     * @mbg.generated
     */
    private Long countRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.count_write
     *
     * @mbg.generated
     */
    private Long countWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.total_latency
     *
     * @mbg.generated
     */
    private String totalLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.avg_latency
     *
     * @mbg.generated
     */
    private String avgLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.max_latency
     *
     * @mbg.generated
     */
    private String maxLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.read_latency
     *
     * @mbg.generated
     */
    private String readLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.write_latency
     *
     * @mbg.generated
     */
    private String writeLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.misc_latency
     *
     * @mbg.generated
     */
    private String miscLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.total_read
     *
     * @mbg.generated
     */
    private String totalRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.avg_read
     *
     * @mbg.generated
     */
    private String avgRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.total_written
     *
     * @mbg.generated
     */
    private String totalWritten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column io_global_by_wait_by_latency.avg_written
     *
     * @mbg.generated
     */
    private String avgWritten;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.event_name
     *
     * @return the value of io_global_by_wait_by_latency.event_name
     *
     * @mbg.generated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.event_name
     *
     * @param eventName the value for io_global_by_wait_by_latency.event_name
     *
     * @mbg.generated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.total
     *
     * @return the value of io_global_by_wait_by_latency.total
     *
     * @mbg.generated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.total
     *
     * @param total the value for io_global_by_wait_by_latency.total
     *
     * @mbg.generated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.count_read
     *
     * @return the value of io_global_by_wait_by_latency.count_read
     *
     * @mbg.generated
     */
    public Long getCountRead() {
        return countRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.count_read
     *
     * @param countRead the value for io_global_by_wait_by_latency.count_read
     *
     * @mbg.generated
     */
    public void setCountRead(Long countRead) {
        this.countRead = countRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.count_write
     *
     * @return the value of io_global_by_wait_by_latency.count_write
     *
     * @mbg.generated
     */
    public Long getCountWrite() {
        return countWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.count_write
     *
     * @param countWrite the value for io_global_by_wait_by_latency.count_write
     *
     * @mbg.generated
     */
    public void setCountWrite(Long countWrite) {
        this.countWrite = countWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.total_latency
     *
     * @return the value of io_global_by_wait_by_latency.total_latency
     *
     * @mbg.generated
     */
    public String getTotalLatency() {
        return totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.total_latency
     *
     * @param totalLatency the value for io_global_by_wait_by_latency.total_latency
     *
     * @mbg.generated
     */
    public void setTotalLatency(String totalLatency) {
        this.totalLatency = totalLatency == null ? null : totalLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.avg_latency
     *
     * @return the value of io_global_by_wait_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public String getAvgLatency() {
        return avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.avg_latency
     *
     * @param avgLatency the value for io_global_by_wait_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public void setAvgLatency(String avgLatency) {
        this.avgLatency = avgLatency == null ? null : avgLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.max_latency
     *
     * @return the value of io_global_by_wait_by_latency.max_latency
     *
     * @mbg.generated
     */
    public String getMaxLatency() {
        return maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.max_latency
     *
     * @param maxLatency the value for io_global_by_wait_by_latency.max_latency
     *
     * @mbg.generated
     */
    public void setMaxLatency(String maxLatency) {
        this.maxLatency = maxLatency == null ? null : maxLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.read_latency
     *
     * @return the value of io_global_by_wait_by_latency.read_latency
     *
     * @mbg.generated
     */
    public String getReadLatency() {
        return readLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.read_latency
     *
     * @param readLatency the value for io_global_by_wait_by_latency.read_latency
     *
     * @mbg.generated
     */
    public void setReadLatency(String readLatency) {
        this.readLatency = readLatency == null ? null : readLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.write_latency
     *
     * @return the value of io_global_by_wait_by_latency.write_latency
     *
     * @mbg.generated
     */
    public String getWriteLatency() {
        return writeLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.write_latency
     *
     * @param writeLatency the value for io_global_by_wait_by_latency.write_latency
     *
     * @mbg.generated
     */
    public void setWriteLatency(String writeLatency) {
        this.writeLatency = writeLatency == null ? null : writeLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.misc_latency
     *
     * @return the value of io_global_by_wait_by_latency.misc_latency
     *
     * @mbg.generated
     */
    public String getMiscLatency() {
        return miscLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.misc_latency
     *
     * @param miscLatency the value for io_global_by_wait_by_latency.misc_latency
     *
     * @mbg.generated
     */
    public void setMiscLatency(String miscLatency) {
        this.miscLatency = miscLatency == null ? null : miscLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.total_read
     *
     * @return the value of io_global_by_wait_by_latency.total_read
     *
     * @mbg.generated
     */
    public String getTotalRead() {
        return totalRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.total_read
     *
     * @param totalRead the value for io_global_by_wait_by_latency.total_read
     *
     * @mbg.generated
     */
    public void setTotalRead(String totalRead) {
        this.totalRead = totalRead == null ? null : totalRead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.avg_read
     *
     * @return the value of io_global_by_wait_by_latency.avg_read
     *
     * @mbg.generated
     */
    public String getAvgRead() {
        return avgRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.avg_read
     *
     * @param avgRead the value for io_global_by_wait_by_latency.avg_read
     *
     * @mbg.generated
     */
    public void setAvgRead(String avgRead) {
        this.avgRead = avgRead == null ? null : avgRead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.total_written
     *
     * @return the value of io_global_by_wait_by_latency.total_written
     *
     * @mbg.generated
     */
    public String getTotalWritten() {
        return totalWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.total_written
     *
     * @param totalWritten the value for io_global_by_wait_by_latency.total_written
     *
     * @mbg.generated
     */
    public void setTotalWritten(String totalWritten) {
        this.totalWritten = totalWritten == null ? null : totalWritten.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column io_global_by_wait_by_latency.avg_written
     *
     * @return the value of io_global_by_wait_by_latency.avg_written
     *
     * @mbg.generated
     */
    public String getAvgWritten() {
        return avgWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column io_global_by_wait_by_latency.avg_written
     *
     * @param avgWritten the value for io_global_by_wait_by_latency.avg_written
     *
     * @mbg.generated
     */
    public void setAvgWritten(String avgWritten) {
        this.avgWritten = avgWritten == null ? null : avgWritten.trim();
    }
}