package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table latest_file_io
 */
public class LatestFileIo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_file_io.thread
     *
     * @mbg.generated
     */
    private String thread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_file_io.file
     *
     * @mbg.generated
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_file_io.operation
     *
     * @mbg.generated
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_file_io.latency
     *
     * @mbg.generated
     */
    private String latency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column latest_file_io.requested
     *
     * @mbg.generated
     */
    private String requested;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_file_io.thread
     *
     * @return the value of latest_file_io.thread
     *
     * @mbg.generated
     */
    public String getThread() {
        return thread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_file_io.thread
     *
     * @param thread the value for latest_file_io.thread
     *
     * @mbg.generated
     */
    public void setThread(String thread) {
        this.thread = thread == null ? null : thread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_file_io.file
     *
     * @return the value of latest_file_io.file
     *
     * @mbg.generated
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_file_io.file
     *
     * @param file the value for latest_file_io.file
     *
     * @mbg.generated
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_file_io.operation
     *
     * @return the value of latest_file_io.operation
     *
     * @mbg.generated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_file_io.operation
     *
     * @param operation the value for latest_file_io.operation
     *
     * @mbg.generated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_file_io.latency
     *
     * @return the value of latest_file_io.latency
     *
     * @mbg.generated
     */
    public String getLatency() {
        return latency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_file_io.latency
     *
     * @param latency the value for latest_file_io.latency
     *
     * @mbg.generated
     */
    public void setLatency(String latency) {
        this.latency = latency == null ? null : latency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column latest_file_io.requested
     *
     * @return the value of latest_file_io.requested
     *
     * @mbg.generated
     */
    public String getRequested() {
        return requested;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column latest_file_io.requested
     *
     * @param requested the value for latest_file_io.requested
     *
     * @mbg.generated
     */
    public void setRequested(String requested) {
        this.requested = requested == null ? null : requested.trim();
    }
}