package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table memory_global_by_current_bytes
 */
public class MemoryGlobalByCurrentBytes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_global_by_current_bytes.event_name
     *
     * @mbg.generated
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_global_by_current_bytes.current_count
     *
     * @mbg.generated
     */
    private Long currentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_global_by_current_bytes.high_count
     *
     * @mbg.generated
     */
    private Long highCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_global_by_current_bytes.current_alloc
     *
     * @mbg.generated
     */
    private String currentAlloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_global_by_current_bytes.current_avg_alloc
     *
     * @mbg.generated
     */
    private String currentAvgAlloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_global_by_current_bytes.high_alloc
     *
     * @mbg.generated
     */
    private String highAlloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_global_by_current_bytes.high_avg_alloc
     *
     * @mbg.generated
     */
    private String highAvgAlloc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_global_by_current_bytes.event_name
     *
     * @return the value of memory_global_by_current_bytes.event_name
     *
     * @mbg.generated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_global_by_current_bytes.event_name
     *
     * @param eventName the value for memory_global_by_current_bytes.event_name
     *
     * @mbg.generated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_global_by_current_bytes.current_count
     *
     * @return the value of memory_global_by_current_bytes.current_count
     *
     * @mbg.generated
     */
    public Long getCurrentCount() {
        return currentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_global_by_current_bytes.current_count
     *
     * @param currentCount the value for memory_global_by_current_bytes.current_count
     *
     * @mbg.generated
     */
    public void setCurrentCount(Long currentCount) {
        this.currentCount = currentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_global_by_current_bytes.high_count
     *
     * @return the value of memory_global_by_current_bytes.high_count
     *
     * @mbg.generated
     */
    public Long getHighCount() {
        return highCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_global_by_current_bytes.high_count
     *
     * @param highCount the value for memory_global_by_current_bytes.high_count
     *
     * @mbg.generated
     */
    public void setHighCount(Long highCount) {
        this.highCount = highCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_global_by_current_bytes.current_alloc
     *
     * @return the value of memory_global_by_current_bytes.current_alloc
     *
     * @mbg.generated
     */
    public String getCurrentAlloc() {
        return currentAlloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_global_by_current_bytes.current_alloc
     *
     * @param currentAlloc the value for memory_global_by_current_bytes.current_alloc
     *
     * @mbg.generated
     */
    public void setCurrentAlloc(String currentAlloc) {
        this.currentAlloc = currentAlloc == null ? null : currentAlloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_global_by_current_bytes.current_avg_alloc
     *
     * @return the value of memory_global_by_current_bytes.current_avg_alloc
     *
     * @mbg.generated
     */
    public String getCurrentAvgAlloc() {
        return currentAvgAlloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_global_by_current_bytes.current_avg_alloc
     *
     * @param currentAvgAlloc the value for memory_global_by_current_bytes.current_avg_alloc
     *
     * @mbg.generated
     */
    public void setCurrentAvgAlloc(String currentAvgAlloc) {
        this.currentAvgAlloc = currentAvgAlloc == null ? null : currentAvgAlloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_global_by_current_bytes.high_alloc
     *
     * @return the value of memory_global_by_current_bytes.high_alloc
     *
     * @mbg.generated
     */
    public String getHighAlloc() {
        return highAlloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_global_by_current_bytes.high_alloc
     *
     * @param highAlloc the value for memory_global_by_current_bytes.high_alloc
     *
     * @mbg.generated
     */
    public void setHighAlloc(String highAlloc) {
        this.highAlloc = highAlloc == null ? null : highAlloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_global_by_current_bytes.high_avg_alloc
     *
     * @return the value of memory_global_by_current_bytes.high_avg_alloc
     *
     * @mbg.generated
     */
    public String getHighAvgAlloc() {
        return highAvgAlloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_global_by_current_bytes.high_avg_alloc
     *
     * @param highAvgAlloc the value for memory_global_by_current_bytes.high_avg_alloc
     *
     * @mbg.generated
     */
    public void setHighAvgAlloc(String highAvgAlloc) {
        this.highAvgAlloc = highAvgAlloc == null ? null : highAvgAlloc.trim();
    }
}