package test.model;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table memory_by_user_by_current_bytes
 */
public class MemoryByUserByCurrentBytes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_by_user_by_current_bytes.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_by_user_by_current_bytes.current_count_used
     *
     * @mbg.generated
     */
    private BigDecimal currentCountUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_by_user_by_current_bytes.current_allocated
     *
     * @mbg.generated
     */
    private String currentAllocated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_by_user_by_current_bytes.current_avg_alloc
     *
     * @mbg.generated
     */
    private String currentAvgAlloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_by_user_by_current_bytes.current_max_alloc
     *
     * @mbg.generated
     */
    private String currentMaxAlloc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memory_by_user_by_current_bytes.total_allocated
     *
     * @mbg.generated
     */
    private String totalAllocated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_by_user_by_current_bytes.user
     *
     * @return the value of memory_by_user_by_current_bytes.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_by_user_by_current_bytes.user
     *
     * @param user the value for memory_by_user_by_current_bytes.user
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_by_user_by_current_bytes.current_count_used
     *
     * @return the value of memory_by_user_by_current_bytes.current_count_used
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentCountUsed() {
        return currentCountUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_by_user_by_current_bytes.current_count_used
     *
     * @param currentCountUsed the value for memory_by_user_by_current_bytes.current_count_used
     *
     * @mbg.generated
     */
    public void setCurrentCountUsed(BigDecimal currentCountUsed) {
        this.currentCountUsed = currentCountUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_by_user_by_current_bytes.current_allocated
     *
     * @return the value of memory_by_user_by_current_bytes.current_allocated
     *
     * @mbg.generated
     */
    public String getCurrentAllocated() {
        return currentAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_by_user_by_current_bytes.current_allocated
     *
     * @param currentAllocated the value for memory_by_user_by_current_bytes.current_allocated
     *
     * @mbg.generated
     */
    public void setCurrentAllocated(String currentAllocated) {
        this.currentAllocated = currentAllocated == null ? null : currentAllocated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_by_user_by_current_bytes.current_avg_alloc
     *
     * @return the value of memory_by_user_by_current_bytes.current_avg_alloc
     *
     * @mbg.generated
     */
    public String getCurrentAvgAlloc() {
        return currentAvgAlloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_by_user_by_current_bytes.current_avg_alloc
     *
     * @param currentAvgAlloc the value for memory_by_user_by_current_bytes.current_avg_alloc
     *
     * @mbg.generated
     */
    public void setCurrentAvgAlloc(String currentAvgAlloc) {
        this.currentAvgAlloc = currentAvgAlloc == null ? null : currentAvgAlloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_by_user_by_current_bytes.current_max_alloc
     *
     * @return the value of memory_by_user_by_current_bytes.current_max_alloc
     *
     * @mbg.generated
     */
    public String getCurrentMaxAlloc() {
        return currentMaxAlloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_by_user_by_current_bytes.current_max_alloc
     *
     * @param currentMaxAlloc the value for memory_by_user_by_current_bytes.current_max_alloc
     *
     * @mbg.generated
     */
    public void setCurrentMaxAlloc(String currentMaxAlloc) {
        this.currentMaxAlloc = currentMaxAlloc == null ? null : currentMaxAlloc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memory_by_user_by_current_bytes.total_allocated
     *
     * @return the value of memory_by_user_by_current_bytes.total_allocated
     *
     * @mbg.generated
     */
    public String getTotalAllocated() {
        return totalAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memory_by_user_by_current_bytes.total_allocated
     *
     * @param totalAllocated the value for memory_by_user_by_current_bytes.total_allocated
     *
     * @mbg.generated
     */
    public void setTotalAllocated(String totalAllocated) {
        this.totalAllocated = totalAllocated == null ? null : totalAllocated.trim();
    }
}