package test.model;

/**
 * Database Table Remarks:
 *   MySQL plugins
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table plugin
 */
public class Plugin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.dl
     *
     * @mbg.generated
     */
    private String dl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.name
     *
     * @return the value of plugin.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.name
     *
     * @param name the value for plugin.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.dl
     *
     * @return the value of plugin.dl
     *
     * @mbg.generated
     */
    public String getDl() {
        return dl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.dl
     *
     * @param dl the value for plugin.dl
     *
     * @mbg.generated
     */
    public void setDl(String dl) {
        this.dl = dl == null ? null : dl.trim();
    }
}