package test.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   Procedure privileges
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table procs_priv
 */
public class ProcsPriv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.Host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.Db
     *
     * @mbg.generated
     */
    private String db;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.User
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.Routine_name
     *
     * @mbg.generated
     */
    private String routineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.Routine_type
     *
     * @mbg.generated
     */
    private String routineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.Grantor
     *
     * @mbg.generated
     */
    private String grantor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.Proc_priv
     *
     * @mbg.generated
     */
    private String procPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procs_priv.Timestamp
     *
     * @mbg.generated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.Host
     *
     * @return the value of procs_priv.Host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.Host
     *
     * @param host the value for procs_priv.Host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.Db
     *
     * @return the value of procs_priv.Db
     *
     * @mbg.generated
     */
    public String getDb() {
        return db;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.Db
     *
     * @param db the value for procs_priv.Db
     *
     * @mbg.generated
     */
    public void setDb(String db) {
        this.db = db == null ? null : db.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.User
     *
     * @return the value of procs_priv.User
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.User
     *
     * @param user the value for procs_priv.User
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.Routine_name
     *
     * @return the value of procs_priv.Routine_name
     *
     * @mbg.generated
     */
    public String getRoutineName() {
        return routineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.Routine_name
     *
     * @param routineName the value for procs_priv.Routine_name
     *
     * @mbg.generated
     */
    public void setRoutineName(String routineName) {
        this.routineName = routineName == null ? null : routineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.Routine_type
     *
     * @return the value of procs_priv.Routine_type
     *
     * @mbg.generated
     */
    public String getRoutineType() {
        return routineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.Routine_type
     *
     * @param routineType the value for procs_priv.Routine_type
     *
     * @mbg.generated
     */
    public void setRoutineType(String routineType) {
        this.routineType = routineType == null ? null : routineType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.Grantor
     *
     * @return the value of procs_priv.Grantor
     *
     * @mbg.generated
     */
    public String getGrantor() {
        return grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.Grantor
     *
     * @param grantor the value for procs_priv.Grantor
     *
     * @mbg.generated
     */
    public void setGrantor(String grantor) {
        this.grantor = grantor == null ? null : grantor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.Proc_priv
     *
     * @return the value of procs_priv.Proc_priv
     *
     * @mbg.generated
     */
    public String getProcPriv() {
        return procPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.Proc_priv
     *
     * @param procPriv the value for procs_priv.Proc_priv
     *
     * @mbg.generated
     */
    public void setProcPriv(String procPriv) {
        this.procPriv = procPriv == null ? null : procPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procs_priv.Timestamp
     *
     * @return the value of procs_priv.Timestamp
     *
     * @mbg.generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procs_priv.Timestamp
     *
     * @param timestamp the value for procs_priv.Timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}