package test.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   User proxy privileges
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table proxies_priv
 */
public class ProxiesPriv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.User
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Proxied_host
     *
     * @mbg.generated
     */
    private String proxiedHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Proxied_user
     *
     * @mbg.generated
     */
    private String proxiedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.With_grant
     *
     * @mbg.generated
     */
    private Boolean withGrant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Grantor
     *
     * @mbg.generated
     */
    private String grantor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxies_priv.Timestamp
     *
     * @mbg.generated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Host
     *
     * @return the value of proxies_priv.Host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Host
     *
     * @param host the value for proxies_priv.Host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.User
     *
     * @return the value of proxies_priv.User
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.User
     *
     * @param user the value for proxies_priv.User
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Proxied_host
     *
     * @return the value of proxies_priv.Proxied_host
     *
     * @mbg.generated
     */
    public String getProxiedHost() {
        return proxiedHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Proxied_host
     *
     * @param proxiedHost the value for proxies_priv.Proxied_host
     *
     * @mbg.generated
     */
    public void setProxiedHost(String proxiedHost) {
        this.proxiedHost = proxiedHost == null ? null : proxiedHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Proxied_user
     *
     * @return the value of proxies_priv.Proxied_user
     *
     * @mbg.generated
     */
    public String getProxiedUser() {
        return proxiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Proxied_user
     *
     * @param proxiedUser the value for proxies_priv.Proxied_user
     *
     * @mbg.generated
     */
    public void setProxiedUser(String proxiedUser) {
        this.proxiedUser = proxiedUser == null ? null : proxiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.With_grant
     *
     * @return the value of proxies_priv.With_grant
     *
     * @mbg.generated
     */
    public Boolean getWithGrant() {
        return withGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.With_grant
     *
     * @param withGrant the value for proxies_priv.With_grant
     *
     * @mbg.generated
     */
    public void setWithGrant(Boolean withGrant) {
        this.withGrant = withGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Grantor
     *
     * @return the value of proxies_priv.Grantor
     *
     * @mbg.generated
     */
    public String getGrantor() {
        return grantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Grantor
     *
     * @param grantor the value for proxies_priv.Grantor
     *
     * @mbg.generated
     */
    public void setGrantor(String grantor) {
        this.grantor = grantor == null ? null : grantor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxies_priv.Timestamp
     *
     * @return the value of proxies_priv.Timestamp
     *
     * @mbg.generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxies_priv.Timestamp
     *
     * @param timestamp the value for proxies_priv.Timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}