package test.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table replication_applier_filters
 */
public class ReplicationApplierFilters {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_filters.CHANNEL_NAME
     *
     * @mbg.generated
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_filters.FILTER_NAME
     *
     * @mbg.generated
     */
    private String filterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_filters.CONFIGURED_BY
     *
     * @mbg.generated
     */
    private String configuredBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_filters.ACTIVE_SINCE
     *
     * @mbg.generated
     */
    private Date activeSince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_filters.COUNTER
     *
     * @mbg.generated
     */
    private Long counter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_filters.FILTER_RULE
     *
     * @mbg.generated
     */
    private String filterRule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_filters.CHANNEL_NAME
     *
     * @return the value of replication_applier_filters.CHANNEL_NAME
     *
     * @mbg.generated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_filters.CHANNEL_NAME
     *
     * @param channelName the value for replication_applier_filters.CHANNEL_NAME
     *
     * @mbg.generated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_filters.FILTER_NAME
     *
     * @return the value of replication_applier_filters.FILTER_NAME
     *
     * @mbg.generated
     */
    public String getFilterName() {
        return filterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_filters.FILTER_NAME
     *
     * @param filterName the value for replication_applier_filters.FILTER_NAME
     *
     * @mbg.generated
     */
    public void setFilterName(String filterName) {
        this.filterName = filterName == null ? null : filterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_filters.CONFIGURED_BY
     *
     * @return the value of replication_applier_filters.CONFIGURED_BY
     *
     * @mbg.generated
     */
    public String getConfiguredBy() {
        return configuredBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_filters.CONFIGURED_BY
     *
     * @param configuredBy the value for replication_applier_filters.CONFIGURED_BY
     *
     * @mbg.generated
     */
    public void setConfiguredBy(String configuredBy) {
        this.configuredBy = configuredBy == null ? null : configuredBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_filters.ACTIVE_SINCE
     *
     * @return the value of replication_applier_filters.ACTIVE_SINCE
     *
     * @mbg.generated
     */
    public Date getActiveSince() {
        return activeSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_filters.ACTIVE_SINCE
     *
     * @param activeSince the value for replication_applier_filters.ACTIVE_SINCE
     *
     * @mbg.generated
     */
    public void setActiveSince(Date activeSince) {
        this.activeSince = activeSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_filters.COUNTER
     *
     * @return the value of replication_applier_filters.COUNTER
     *
     * @mbg.generated
     */
    public Long getCounter() {
        return counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_filters.COUNTER
     *
     * @param counter the value for replication_applier_filters.COUNTER
     *
     * @mbg.generated
     */
    public void setCounter(Long counter) {
        this.counter = counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_filters.FILTER_RULE
     *
     * @return the value of replication_applier_filters.FILTER_RULE
     *
     * @mbg.generated
     */
    public String getFilterRule() {
        return filterRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_filters.FILTER_RULE
     *
     * @param filterRule the value for replication_applier_filters.FILTER_RULE
     *
     * @mbg.generated
     */
    public void setFilterRule(String filterRule) {
        this.filterRule = filterRule == null ? null : filterRule.trim();
    }
}