package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SCHEMATA
 */
public class Schemata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMATA.CATALOG_NAME
     *
     * @mbg.generated
     */
    private String catalogName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMATA.SCHEMA_NAME
     *
     * @mbg.generated
     */
    private String schemaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMATA.DEFAULT_CHARACTER_SET_NAME
     *
     * @mbg.generated
     */
    private String defaultCharacterSetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMATA.DEFAULT_COLLATION_NAME
     *
     * @mbg.generated
     */
    private String defaultCollationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHEMATA.SQL_PATH
     *
     * @mbg.generated
     */
    private byte[] sqlPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMATA.CATALOG_NAME
     *
     * @return the value of SCHEMATA.CATALOG_NAME
     *
     * @mbg.generated
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMATA.CATALOG_NAME
     *
     * @param catalogName the value for SCHEMATA.CATALOG_NAME
     *
     * @mbg.generated
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName == null ? null : catalogName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMATA.SCHEMA_NAME
     *
     * @return the value of SCHEMATA.SCHEMA_NAME
     *
     * @mbg.generated
     */
    public String getSchemaName() {
        return schemaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMATA.SCHEMA_NAME
     *
     * @param schemaName the value for SCHEMATA.SCHEMA_NAME
     *
     * @mbg.generated
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName == null ? null : schemaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMATA.DEFAULT_CHARACTER_SET_NAME
     *
     * @return the value of SCHEMATA.DEFAULT_CHARACTER_SET_NAME
     *
     * @mbg.generated
     */
    public String getDefaultCharacterSetName() {
        return defaultCharacterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMATA.DEFAULT_CHARACTER_SET_NAME
     *
     * @param defaultCharacterSetName the value for SCHEMATA.DEFAULT_CHARACTER_SET_NAME
     *
     * @mbg.generated
     */
    public void setDefaultCharacterSetName(String defaultCharacterSetName) {
        this.defaultCharacterSetName = defaultCharacterSetName == null ? null : defaultCharacterSetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMATA.DEFAULT_COLLATION_NAME
     *
     * @return the value of SCHEMATA.DEFAULT_COLLATION_NAME
     *
     * @mbg.generated
     */
    public String getDefaultCollationName() {
        return defaultCollationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMATA.DEFAULT_COLLATION_NAME
     *
     * @param defaultCollationName the value for SCHEMATA.DEFAULT_COLLATION_NAME
     *
     * @mbg.generated
     */
    public void setDefaultCollationName(String defaultCollationName) {
        this.defaultCollationName = defaultCollationName == null ? null : defaultCollationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHEMATA.SQL_PATH
     *
     * @return the value of SCHEMATA.SQL_PATH
     *
     * @mbg.generated
     */
    public byte[] getSqlPath() {
        return sqlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHEMATA.SQL_PATH
     *
     * @param sqlPath the value for SCHEMATA.SQL_PATH
     *
     * @mbg.generated
     */
    public void setSqlPath(byte[] sqlPath) {
        this.sqlPath = sqlPath;
    }
}