package test.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table server_cost
 */
public class ServerCost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_cost.cost_name
     *
     * @mbg.generated
     */
    private String costName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_cost.cost_value
     *
     * @mbg.generated
     */
    private Float costValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_cost.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_cost.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_cost.default_value
     *
     * @mbg.generated
     */
    private Float defaultValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_cost.cost_name
     *
     * @return the value of server_cost.cost_name
     *
     * @mbg.generated
     */
    public String getCostName() {
        return costName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_cost.cost_name
     *
     * @param costName the value for server_cost.cost_name
     *
     * @mbg.generated
     */
    public void setCostName(String costName) {
        this.costName = costName == null ? null : costName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_cost.cost_value
     *
     * @return the value of server_cost.cost_value
     *
     * @mbg.generated
     */
    public Float getCostValue() {
        return costValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_cost.cost_value
     *
     * @param costValue the value for server_cost.cost_value
     *
     * @mbg.generated
     */
    public void setCostValue(Float costValue) {
        this.costValue = costValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_cost.last_update
     *
     * @return the value of server_cost.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_cost.last_update
     *
     * @param lastUpdate the value for server_cost.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_cost.comment
     *
     * @return the value of server_cost.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_cost.comment
     *
     * @param comment the value for server_cost.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_cost.default_value
     *
     * @return the value of server_cost.default_value
     *
     * @mbg.generated
     */
    public Float getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_cost.default_value
     *
     * @param defaultValue the value for server_cost.default_value
     *
     * @mbg.generated
     */
    public void setDefaultValue(Float defaultValue) {
        this.defaultValue = defaultValue;
    }
}