package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table setup_instruments
 */
public class SetupInstruments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_instruments.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_instruments.ENABLED
     *
     * @mbg.generated
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_instruments.TIMED
     *
     * @mbg.generated
     */
    private String timed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_instruments.PROPERTIES
     *
     * @mbg.generated
     */
    private String properties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_instruments.VOLATILITY
     *
     * @mbg.generated
     */
    private Integer volatility;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_instruments.DOCUMENTATION
     *
     * @mbg.generated
     */
    private String documentation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_instruments.NAME
     *
     * @return the value of setup_instruments.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_instruments.NAME
     *
     * @param name the value for setup_instruments.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_instruments.ENABLED
     *
     * @return the value of setup_instruments.ENABLED
     *
     * @mbg.generated
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_instruments.ENABLED
     *
     * @param enabled the value for setup_instruments.ENABLED
     *
     * @mbg.generated
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_instruments.TIMED
     *
     * @return the value of setup_instruments.TIMED
     *
     * @mbg.generated
     */
    public String getTimed() {
        return timed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_instruments.TIMED
     *
     * @param timed the value for setup_instruments.TIMED
     *
     * @mbg.generated
     */
    public void setTimed(String timed) {
        this.timed = timed == null ? null : timed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_instruments.PROPERTIES
     *
     * @return the value of setup_instruments.PROPERTIES
     *
     * @mbg.generated
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_instruments.PROPERTIES
     *
     * @param properties the value for setup_instruments.PROPERTIES
     *
     * @mbg.generated
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_instruments.VOLATILITY
     *
     * @return the value of setup_instruments.VOLATILITY
     *
     * @mbg.generated
     */
    public Integer getVolatility() {
        return volatility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_instruments.VOLATILITY
     *
     * @param volatility the value for setup_instruments.VOLATILITY
     *
     * @mbg.generated
     */
    public void setVolatility(Integer volatility) {
        this.volatility = volatility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_instruments.DOCUMENTATION
     *
     * @return the value of setup_instruments.DOCUMENTATION
     *
     * @mbg.generated
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_instruments.DOCUMENTATION
     *
     * @param documentation the value for setup_instruments.DOCUMENTATION
     *
     * @mbg.generated
     */
    public void setDocumentation(String documentation) {
        this.documentation = documentation == null ? null : documentation.trim();
    }
}