package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table status_by_user
 */
public class StatusByUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_by_user.USER
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_by_user.VARIABLE_NAME
     *
     * @mbg.generated
     */
    private String variableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_by_user.VARIABLE_VALUE
     *
     * @mbg.generated
     */
    private String variableValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_by_user.USER
     *
     * @return the value of status_by_user.USER
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_by_user.USER
     *
     * @param user the value for status_by_user.USER
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_by_user.VARIABLE_NAME
     *
     * @return the value of status_by_user.VARIABLE_NAME
     *
     * @mbg.generated
     */
    public String getVariableName() {
        return variableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_by_user.VARIABLE_NAME
     *
     * @param variableName the value for status_by_user.VARIABLE_NAME
     *
     * @mbg.generated
     */
    public void setVariableName(String variableName) {
        this.variableName = variableName == null ? null : variableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_by_user.VARIABLE_VALUE
     *
     * @return the value of status_by_user.VARIABLE_VALUE
     *
     * @mbg.generated
     */
    public String getVariableValue() {
        return variableValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_by_user.VARIABLE_VALUE
     *
     * @param variableValue the value for status_by_user.VARIABLE_VALUE
     *
     * @mbg.generated
     */
    public void setVariableValue(String variableValue) {
        this.variableValue = variableValue == null ? null : variableValue.trim();
    }
}