package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table threads
 */
public class Threads {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.THREAD_ID
     *
     * @mbg.generated
     */
    private Long threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_ID
     *
     * @mbg.generated
     */
    private Long processlistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_USER
     *
     * @mbg.generated
     */
    private String processlistUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_HOST
     *
     * @mbg.generated
     */
    private String processlistHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_DB
     *
     * @mbg.generated
     */
    private String processlistDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_COMMAND
     *
     * @mbg.generated
     */
    private String processlistCommand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_TIME
     *
     * @mbg.generated
     */
    private Long processlistTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_STATE
     *
     * @mbg.generated
     */
    private String processlistState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PARENT_THREAD_ID
     *
     * @mbg.generated
     */
    private Long parentThreadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.ROLE
     *
     * @mbg.generated
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.INSTRUMENTED
     *
     * @mbg.generated
     */
    private String instrumented;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.HISTORY
     *
     * @mbg.generated
     */
    private String history;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.CONNECTION_TYPE
     *
     * @mbg.generated
     */
    private String connectionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.THREAD_OS_ID
     *
     * @mbg.generated
     */
    private Long threadOsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.RESOURCE_GROUP
     *
     * @mbg.generated
     */
    private String resourceGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threads.PROCESSLIST_INFO
     *
     * @mbg.generated
     */
    private String processlistInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.THREAD_ID
     *
     * @return the value of threads.THREAD_ID
     *
     * @mbg.generated
     */
    public Long getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.THREAD_ID
     *
     * @param threadId the value for threads.THREAD_ID
     *
     * @mbg.generated
     */
    public void setThreadId(Long threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.NAME
     *
     * @return the value of threads.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.NAME
     *
     * @param name the value for threads.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.TYPE
     *
     * @return the value of threads.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.TYPE
     *
     * @param type the value for threads.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_ID
     *
     * @return the value of threads.PROCESSLIST_ID
     *
     * @mbg.generated
     */
    public Long getProcesslistId() {
        return processlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_ID
     *
     * @param processlistId the value for threads.PROCESSLIST_ID
     *
     * @mbg.generated
     */
    public void setProcesslistId(Long processlistId) {
        this.processlistId = processlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_USER
     *
     * @return the value of threads.PROCESSLIST_USER
     *
     * @mbg.generated
     */
    public String getProcesslistUser() {
        return processlistUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_USER
     *
     * @param processlistUser the value for threads.PROCESSLIST_USER
     *
     * @mbg.generated
     */
    public void setProcesslistUser(String processlistUser) {
        this.processlistUser = processlistUser == null ? null : processlistUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_HOST
     *
     * @return the value of threads.PROCESSLIST_HOST
     *
     * @mbg.generated
     */
    public String getProcesslistHost() {
        return processlistHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_HOST
     *
     * @param processlistHost the value for threads.PROCESSLIST_HOST
     *
     * @mbg.generated
     */
    public void setProcesslistHost(String processlistHost) {
        this.processlistHost = processlistHost == null ? null : processlistHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_DB
     *
     * @return the value of threads.PROCESSLIST_DB
     *
     * @mbg.generated
     */
    public String getProcesslistDb() {
        return processlistDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_DB
     *
     * @param processlistDb the value for threads.PROCESSLIST_DB
     *
     * @mbg.generated
     */
    public void setProcesslistDb(String processlistDb) {
        this.processlistDb = processlistDb == null ? null : processlistDb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_COMMAND
     *
     * @return the value of threads.PROCESSLIST_COMMAND
     *
     * @mbg.generated
     */
    public String getProcesslistCommand() {
        return processlistCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_COMMAND
     *
     * @param processlistCommand the value for threads.PROCESSLIST_COMMAND
     *
     * @mbg.generated
     */
    public void setProcesslistCommand(String processlistCommand) {
        this.processlistCommand = processlistCommand == null ? null : processlistCommand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_TIME
     *
     * @return the value of threads.PROCESSLIST_TIME
     *
     * @mbg.generated
     */
    public Long getProcesslistTime() {
        return processlistTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_TIME
     *
     * @param processlistTime the value for threads.PROCESSLIST_TIME
     *
     * @mbg.generated
     */
    public void setProcesslistTime(Long processlistTime) {
        this.processlistTime = processlistTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_STATE
     *
     * @return the value of threads.PROCESSLIST_STATE
     *
     * @mbg.generated
     */
    public String getProcesslistState() {
        return processlistState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_STATE
     *
     * @param processlistState the value for threads.PROCESSLIST_STATE
     *
     * @mbg.generated
     */
    public void setProcesslistState(String processlistState) {
        this.processlistState = processlistState == null ? null : processlistState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PARENT_THREAD_ID
     *
     * @return the value of threads.PARENT_THREAD_ID
     *
     * @mbg.generated
     */
    public Long getParentThreadId() {
        return parentThreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PARENT_THREAD_ID
     *
     * @param parentThreadId the value for threads.PARENT_THREAD_ID
     *
     * @mbg.generated
     */
    public void setParentThreadId(Long parentThreadId) {
        this.parentThreadId = parentThreadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.ROLE
     *
     * @return the value of threads.ROLE
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.ROLE
     *
     * @param role the value for threads.ROLE
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.INSTRUMENTED
     *
     * @return the value of threads.INSTRUMENTED
     *
     * @mbg.generated
     */
    public String getInstrumented() {
        return instrumented;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.INSTRUMENTED
     *
     * @param instrumented the value for threads.INSTRUMENTED
     *
     * @mbg.generated
     */
    public void setInstrumented(String instrumented) {
        this.instrumented = instrumented == null ? null : instrumented.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.HISTORY
     *
     * @return the value of threads.HISTORY
     *
     * @mbg.generated
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.HISTORY
     *
     * @param history the value for threads.HISTORY
     *
     * @mbg.generated
     */
    public void setHistory(String history) {
        this.history = history == null ? null : history.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.CONNECTION_TYPE
     *
     * @return the value of threads.CONNECTION_TYPE
     *
     * @mbg.generated
     */
    public String getConnectionType() {
        return connectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.CONNECTION_TYPE
     *
     * @param connectionType the value for threads.CONNECTION_TYPE
     *
     * @mbg.generated
     */
    public void setConnectionType(String connectionType) {
        this.connectionType = connectionType == null ? null : connectionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.THREAD_OS_ID
     *
     * @return the value of threads.THREAD_OS_ID
     *
     * @mbg.generated
     */
    public Long getThreadOsId() {
        return threadOsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.THREAD_OS_ID
     *
     * @param threadOsId the value for threads.THREAD_OS_ID
     *
     * @mbg.generated
     */
    public void setThreadOsId(Long threadOsId) {
        this.threadOsId = threadOsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.RESOURCE_GROUP
     *
     * @return the value of threads.RESOURCE_GROUP
     *
     * @mbg.generated
     */
    public String getResourceGroup() {
        return resourceGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.RESOURCE_GROUP
     *
     * @param resourceGroup the value for threads.RESOURCE_GROUP
     *
     * @mbg.generated
     */
    public void setResourceGroup(String resourceGroup) {
        this.resourceGroup = resourceGroup == null ? null : resourceGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threads.PROCESSLIST_INFO
     *
     * @return the value of threads.PROCESSLIST_INFO
     *
     * @mbg.generated
     */
    public String getProcesslistInfo() {
        return processlistInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threads.PROCESSLIST_INFO
     *
     * @param processlistInfo the value for threads.PROCESSLIST_INFO
     *
     * @mbg.generated
     */
    public void setProcesslistInfo(String processlistInfo) {
        this.processlistInfo = processlistInfo == null ? null : processlistInfo.trim();
    }
}