package test.model;

/**
 * Database Table Remarks:
 *   Time zone transition types
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table time_zone_transition_type
 */
public class TimeZoneTransitionType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_zone_transition_type.Time_zone_id
     *
     * @mbg.generated
     */
    private Integer timeZoneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_zone_transition_type.Transition_type_id
     *
     * @mbg.generated
     */
    private Integer transitionTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_zone_transition_type.Offset
     *
     * @mbg.generated
     */
    private Integer offset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_zone_transition_type.Is_DST
     *
     * @mbg.generated
     */
    private Byte isDst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_zone_transition_type.Abbreviation
     *
     * @mbg.generated
     */
    private String abbreviation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_zone_transition_type.Time_zone_id
     *
     * @return the value of time_zone_transition_type.Time_zone_id
     *
     * @mbg.generated
     */
    public Integer getTimeZoneId() {
        return timeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_zone_transition_type.Time_zone_id
     *
     * @param timeZoneId the value for time_zone_transition_type.Time_zone_id
     *
     * @mbg.generated
     */
    public void setTimeZoneId(Integer timeZoneId) {
        this.timeZoneId = timeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_zone_transition_type.Transition_type_id
     *
     * @return the value of time_zone_transition_type.Transition_type_id
     *
     * @mbg.generated
     */
    public Integer getTransitionTypeId() {
        return transitionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_zone_transition_type.Transition_type_id
     *
     * @param transitionTypeId the value for time_zone_transition_type.Transition_type_id
     *
     * @mbg.generated
     */
    public void setTransitionTypeId(Integer transitionTypeId) {
        this.transitionTypeId = transitionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_zone_transition_type.Offset
     *
     * @return the value of time_zone_transition_type.Offset
     *
     * @mbg.generated
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_zone_transition_type.Offset
     *
     * @param offset the value for time_zone_transition_type.Offset
     *
     * @mbg.generated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_zone_transition_type.Is_DST
     *
     * @return the value of time_zone_transition_type.Is_DST
     *
     * @mbg.generated
     */
    public Byte getIsDst() {
        return isDst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_zone_transition_type.Is_DST
     *
     * @param isDst the value for time_zone_transition_type.Is_DST
     *
     * @mbg.generated
     */
    public void setIsDst(Byte isDst) {
        this.isDst = isDst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_zone_transition_type.Abbreviation
     *
     * @return the value of time_zone_transition_type.Abbreviation
     *
     * @mbg.generated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_zone_transition_type.Abbreviation
     *
     * @param abbreviation the value for time_zone_transition_type.Abbreviation
     *
     * @mbg.generated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }
}