package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_summary_by_file_io_type
 */
public class UserSummaryByFileIoType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_summary_by_file_io_type.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_summary_by_file_io_type.event_name
     *
     * @mbg.generated
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_summary_by_file_io_type.total
     *
     * @mbg.generated
     */
    private Long total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_summary_by_file_io_type.latency
     *
     * @mbg.generated
     */
    private String latency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_summary_by_file_io_type.max_latency
     *
     * @mbg.generated
     */
    private String maxLatency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_summary_by_file_io_type.user
     *
     * @return the value of user_summary_by_file_io_type.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_summary_by_file_io_type.user
     *
     * @param user the value for user_summary_by_file_io_type.user
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_summary_by_file_io_type.event_name
     *
     * @return the value of user_summary_by_file_io_type.event_name
     *
     * @mbg.generated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_summary_by_file_io_type.event_name
     *
     * @param eventName the value for user_summary_by_file_io_type.event_name
     *
     * @mbg.generated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_summary_by_file_io_type.total
     *
     * @return the value of user_summary_by_file_io_type.total
     *
     * @mbg.generated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_summary_by_file_io_type.total
     *
     * @param total the value for user_summary_by_file_io_type.total
     *
     * @mbg.generated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_summary_by_file_io_type.latency
     *
     * @return the value of user_summary_by_file_io_type.latency
     *
     * @mbg.generated
     */
    public String getLatency() {
        return latency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_summary_by_file_io_type.latency
     *
     * @param latency the value for user_summary_by_file_io_type.latency
     *
     * @mbg.generated
     */
    public void setLatency(String latency) {
        this.latency = latency == null ? null : latency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_summary_by_file_io_type.max_latency
     *
     * @return the value of user_summary_by_file_io_type.max_latency
     *
     * @mbg.generated
     */
    public String getMaxLatency() {
        return maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_summary_by_file_io_type.max_latency
     *
     * @param maxLatency the value for user_summary_by_file_io_type.max_latency
     *
     * @mbg.generated
     */
    public void setMaxLatency(String maxLatency) {
        this.maxLatency = maxLatency == null ? null : maxLatency.trim();
    }
}