package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table waits_by_user_by_latency
 */
public class WaitsByUserByLatency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waits_by_user_by_latency.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waits_by_user_by_latency.event
     *
     * @mbg.generated
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waits_by_user_by_latency.total
     *
     * @mbg.generated
     */
    private Long total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waits_by_user_by_latency.total_latency
     *
     * @mbg.generated
     */
    private String totalLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waits_by_user_by_latency.avg_latency
     *
     * @mbg.generated
     */
    private String avgLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waits_by_user_by_latency.max_latency
     *
     * @mbg.generated
     */
    private String maxLatency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waits_by_user_by_latency.user
     *
     * @return the value of waits_by_user_by_latency.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waits_by_user_by_latency.user
     *
     * @param user the value for waits_by_user_by_latency.user
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waits_by_user_by_latency.event
     *
     * @return the value of waits_by_user_by_latency.event
     *
     * @mbg.generated
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waits_by_user_by_latency.event
     *
     * @param event the value for waits_by_user_by_latency.event
     *
     * @mbg.generated
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waits_by_user_by_latency.total
     *
     * @return the value of waits_by_user_by_latency.total
     *
     * @mbg.generated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waits_by_user_by_latency.total
     *
     * @param total the value for waits_by_user_by_latency.total
     *
     * @mbg.generated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waits_by_user_by_latency.total_latency
     *
     * @return the value of waits_by_user_by_latency.total_latency
     *
     * @mbg.generated
     */
    public String getTotalLatency() {
        return totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waits_by_user_by_latency.total_latency
     *
     * @param totalLatency the value for waits_by_user_by_latency.total_latency
     *
     * @mbg.generated
     */
    public void setTotalLatency(String totalLatency) {
        this.totalLatency = totalLatency == null ? null : totalLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waits_by_user_by_latency.avg_latency
     *
     * @return the value of waits_by_user_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public String getAvgLatency() {
        return avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waits_by_user_by_latency.avg_latency
     *
     * @param avgLatency the value for waits_by_user_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public void setAvgLatency(String avgLatency) {
        this.avgLatency = avgLatency == null ? null : avgLatency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waits_by_user_by_latency.max_latency
     *
     * @return the value of waits_by_user_by_latency.max_latency
     *
     * @mbg.generated
     */
    public String getMaxLatency() {
        return maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waits_by_user_by_latency.max_latency
     *
     * @param maxLatency the value for waits_by_user_by_latency.max_latency
     *
     * @mbg.generated
     */
    public void setMaxLatency(String maxLatency) {
        this.maxLatency = maxLatency == null ? null : maxLatency.trim();
    }
}