package test.model;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table x$io_by_thread_by_latency
 */
public class XIoByThreadByLatency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.total
     *
     * @mbg.generated
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.total_latency
     *
     * @mbg.generated
     */
    private BigDecimal totalLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.min_latency
     *
     * @mbg.generated
     */
    private Long minLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.avg_latency
     *
     * @mbg.generated
     */
    private BigDecimal avgLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.max_latency
     *
     * @mbg.generated
     */
    private Long maxLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.thread_id
     *
     * @mbg.generated
     */
    private Long threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_by_thread_by_latency.processlist_id
     *
     * @mbg.generated
     */
    private Long processlistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.user
     *
     * @return the value of x$io_by_thread_by_latency.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.user
     *
     * @param user the value for x$io_by_thread_by_latency.user
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.total
     *
     * @return the value of x$io_by_thread_by_latency.total
     *
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.total
     *
     * @param total the value for x$io_by_thread_by_latency.total
     *
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.total_latency
     *
     * @return the value of x$io_by_thread_by_latency.total_latency
     *
     * @mbg.generated
     */
    public BigDecimal getTotalLatency() {
        return totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.total_latency
     *
     * @param totalLatency the value for x$io_by_thread_by_latency.total_latency
     *
     * @mbg.generated
     */
    public void setTotalLatency(BigDecimal totalLatency) {
        this.totalLatency = totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.min_latency
     *
     * @return the value of x$io_by_thread_by_latency.min_latency
     *
     * @mbg.generated
     */
    public Long getMinLatency() {
        return minLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.min_latency
     *
     * @param minLatency the value for x$io_by_thread_by_latency.min_latency
     *
     * @mbg.generated
     */
    public void setMinLatency(Long minLatency) {
        this.minLatency = minLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.avg_latency
     *
     * @return the value of x$io_by_thread_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public BigDecimal getAvgLatency() {
        return avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.avg_latency
     *
     * @param avgLatency the value for x$io_by_thread_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public void setAvgLatency(BigDecimal avgLatency) {
        this.avgLatency = avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.max_latency
     *
     * @return the value of x$io_by_thread_by_latency.max_latency
     *
     * @mbg.generated
     */
    public Long getMaxLatency() {
        return maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.max_latency
     *
     * @param maxLatency the value for x$io_by_thread_by_latency.max_latency
     *
     * @mbg.generated
     */
    public void setMaxLatency(Long maxLatency) {
        this.maxLatency = maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.thread_id
     *
     * @return the value of x$io_by_thread_by_latency.thread_id
     *
     * @mbg.generated
     */
    public Long getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.thread_id
     *
     * @param threadId the value for x$io_by_thread_by_latency.thread_id
     *
     * @mbg.generated
     */
    public void setThreadId(Long threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_by_thread_by_latency.processlist_id
     *
     * @return the value of x$io_by_thread_by_latency.processlist_id
     *
     * @mbg.generated
     */
    public Long getProcesslistId() {
        return processlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_by_thread_by_latency.processlist_id
     *
     * @param processlistId the value for x$io_by_thread_by_latency.processlist_id
     *
     * @mbg.generated
     */
    public void setProcesslistId(Long processlistId) {
        this.processlistId = processlistId;
    }
}