package test.model;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table x$io_global_by_wait_by_bytes
 */
public class XIoGlobalByWaitByBytes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.event_name
     *
     * @mbg.generated
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.total
     *
     * @mbg.generated
     */
    private Long total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.total_latency
     *
     * @mbg.generated
     */
    private Long totalLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.min_latency
     *
     * @mbg.generated
     */
    private Long minLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.avg_latency
     *
     * @mbg.generated
     */
    private Long avgLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.max_latency
     *
     * @mbg.generated
     */
    private Long maxLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.count_read
     *
     * @mbg.generated
     */
    private Long countRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.total_read
     *
     * @mbg.generated
     */
    private Long totalRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.avg_read
     *
     * @mbg.generated
     */
    private BigDecimal avgRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.count_write
     *
     * @mbg.generated
     */
    private Long countWrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.total_written
     *
     * @mbg.generated
     */
    private Long totalWritten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.avg_written
     *
     * @mbg.generated
     */
    private BigDecimal avgWritten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$io_global_by_wait_by_bytes.total_requested
     *
     * @mbg.generated
     */
    private Long totalRequested;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.event_name
     *
     * @return the value of x$io_global_by_wait_by_bytes.event_name
     *
     * @mbg.generated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.event_name
     *
     * @param eventName the value for x$io_global_by_wait_by_bytes.event_name
     *
     * @mbg.generated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.total
     *
     * @return the value of x$io_global_by_wait_by_bytes.total
     *
     * @mbg.generated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.total
     *
     * @param total the value for x$io_global_by_wait_by_bytes.total
     *
     * @mbg.generated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.total_latency
     *
     * @return the value of x$io_global_by_wait_by_bytes.total_latency
     *
     * @mbg.generated
     */
    public Long getTotalLatency() {
        return totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.total_latency
     *
     * @param totalLatency the value for x$io_global_by_wait_by_bytes.total_latency
     *
     * @mbg.generated
     */
    public void setTotalLatency(Long totalLatency) {
        this.totalLatency = totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.min_latency
     *
     * @return the value of x$io_global_by_wait_by_bytes.min_latency
     *
     * @mbg.generated
     */
    public Long getMinLatency() {
        return minLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.min_latency
     *
     * @param minLatency the value for x$io_global_by_wait_by_bytes.min_latency
     *
     * @mbg.generated
     */
    public void setMinLatency(Long minLatency) {
        this.minLatency = minLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.avg_latency
     *
     * @return the value of x$io_global_by_wait_by_bytes.avg_latency
     *
     * @mbg.generated
     */
    public Long getAvgLatency() {
        return avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.avg_latency
     *
     * @param avgLatency the value for x$io_global_by_wait_by_bytes.avg_latency
     *
     * @mbg.generated
     */
    public void setAvgLatency(Long avgLatency) {
        this.avgLatency = avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.max_latency
     *
     * @return the value of x$io_global_by_wait_by_bytes.max_latency
     *
     * @mbg.generated
     */
    public Long getMaxLatency() {
        return maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.max_latency
     *
     * @param maxLatency the value for x$io_global_by_wait_by_bytes.max_latency
     *
     * @mbg.generated
     */
    public void setMaxLatency(Long maxLatency) {
        this.maxLatency = maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.count_read
     *
     * @return the value of x$io_global_by_wait_by_bytes.count_read
     *
     * @mbg.generated
     */
    public Long getCountRead() {
        return countRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.count_read
     *
     * @param countRead the value for x$io_global_by_wait_by_bytes.count_read
     *
     * @mbg.generated
     */
    public void setCountRead(Long countRead) {
        this.countRead = countRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.total_read
     *
     * @return the value of x$io_global_by_wait_by_bytes.total_read
     *
     * @mbg.generated
     */
    public Long getTotalRead() {
        return totalRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.total_read
     *
     * @param totalRead the value for x$io_global_by_wait_by_bytes.total_read
     *
     * @mbg.generated
     */
    public void setTotalRead(Long totalRead) {
        this.totalRead = totalRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.avg_read
     *
     * @return the value of x$io_global_by_wait_by_bytes.avg_read
     *
     * @mbg.generated
     */
    public BigDecimal getAvgRead() {
        return avgRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.avg_read
     *
     * @param avgRead the value for x$io_global_by_wait_by_bytes.avg_read
     *
     * @mbg.generated
     */
    public void setAvgRead(BigDecimal avgRead) {
        this.avgRead = avgRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.count_write
     *
     * @return the value of x$io_global_by_wait_by_bytes.count_write
     *
     * @mbg.generated
     */
    public Long getCountWrite() {
        return countWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.count_write
     *
     * @param countWrite the value for x$io_global_by_wait_by_bytes.count_write
     *
     * @mbg.generated
     */
    public void setCountWrite(Long countWrite) {
        this.countWrite = countWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.total_written
     *
     * @return the value of x$io_global_by_wait_by_bytes.total_written
     *
     * @mbg.generated
     */
    public Long getTotalWritten() {
        return totalWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.total_written
     *
     * @param totalWritten the value for x$io_global_by_wait_by_bytes.total_written
     *
     * @mbg.generated
     */
    public void setTotalWritten(Long totalWritten) {
        this.totalWritten = totalWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.avg_written
     *
     * @return the value of x$io_global_by_wait_by_bytes.avg_written
     *
     * @mbg.generated
     */
    public BigDecimal getAvgWritten() {
        return avgWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.avg_written
     *
     * @param avgWritten the value for x$io_global_by_wait_by_bytes.avg_written
     *
     * @mbg.generated
     */
    public void setAvgWritten(BigDecimal avgWritten) {
        this.avgWritten = avgWritten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$io_global_by_wait_by_bytes.total_requested
     *
     * @return the value of x$io_global_by_wait_by_bytes.total_requested
     *
     * @mbg.generated
     */
    public Long getTotalRequested() {
        return totalRequested;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$io_global_by_wait_by_bytes.total_requested
     *
     * @param totalRequested the value for x$io_global_by_wait_by_bytes.total_requested
     *
     * @mbg.generated
     */
    public void setTotalRequested(Long totalRequested) {
        this.totalRequested = totalRequested;
    }
}