package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table x$schema_index_statistics
 */
public class XSchemaIndexStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.table_schema
     *
     * @mbg.generated
     */
    private String tableSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.index_name
     *
     * @mbg.generated
     */
    private String indexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.rows_selected
     *
     * @mbg.generated
     */
    private Long rowsSelected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.select_latency
     *
     * @mbg.generated
     */
    private Long selectLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.rows_inserted
     *
     * @mbg.generated
     */
    private Long rowsInserted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.insert_latency
     *
     * @mbg.generated
     */
    private Long insertLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.rows_updated
     *
     * @mbg.generated
     */
    private Long rowsUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.update_latency
     *
     * @mbg.generated
     */
    private Long updateLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.rows_deleted
     *
     * @mbg.generated
     */
    private Long rowsDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$schema_index_statistics.delete_latency
     *
     * @mbg.generated
     */
    private Long deleteLatency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.table_schema
     *
     * @return the value of x$schema_index_statistics.table_schema
     *
     * @mbg.generated
     */
    public String getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.table_schema
     *
     * @param tableSchema the value for x$schema_index_statistics.table_schema
     *
     * @mbg.generated
     */
    public void setTableSchema(String tableSchema) {
        this.tableSchema = tableSchema == null ? null : tableSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.table_name
     *
     * @return the value of x$schema_index_statistics.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.table_name
     *
     * @param tableName the value for x$schema_index_statistics.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.index_name
     *
     * @return the value of x$schema_index_statistics.index_name
     *
     * @mbg.generated
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.index_name
     *
     * @param indexName the value for x$schema_index_statistics.index_name
     *
     * @mbg.generated
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.rows_selected
     *
     * @return the value of x$schema_index_statistics.rows_selected
     *
     * @mbg.generated
     */
    public Long getRowsSelected() {
        return rowsSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.rows_selected
     *
     * @param rowsSelected the value for x$schema_index_statistics.rows_selected
     *
     * @mbg.generated
     */
    public void setRowsSelected(Long rowsSelected) {
        this.rowsSelected = rowsSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.select_latency
     *
     * @return the value of x$schema_index_statistics.select_latency
     *
     * @mbg.generated
     */
    public Long getSelectLatency() {
        return selectLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.select_latency
     *
     * @param selectLatency the value for x$schema_index_statistics.select_latency
     *
     * @mbg.generated
     */
    public void setSelectLatency(Long selectLatency) {
        this.selectLatency = selectLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.rows_inserted
     *
     * @return the value of x$schema_index_statistics.rows_inserted
     *
     * @mbg.generated
     */
    public Long getRowsInserted() {
        return rowsInserted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.rows_inserted
     *
     * @param rowsInserted the value for x$schema_index_statistics.rows_inserted
     *
     * @mbg.generated
     */
    public void setRowsInserted(Long rowsInserted) {
        this.rowsInserted = rowsInserted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.insert_latency
     *
     * @return the value of x$schema_index_statistics.insert_latency
     *
     * @mbg.generated
     */
    public Long getInsertLatency() {
        return insertLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.insert_latency
     *
     * @param insertLatency the value for x$schema_index_statistics.insert_latency
     *
     * @mbg.generated
     */
    public void setInsertLatency(Long insertLatency) {
        this.insertLatency = insertLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.rows_updated
     *
     * @return the value of x$schema_index_statistics.rows_updated
     *
     * @mbg.generated
     */
    public Long getRowsUpdated() {
        return rowsUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.rows_updated
     *
     * @param rowsUpdated the value for x$schema_index_statistics.rows_updated
     *
     * @mbg.generated
     */
    public void setRowsUpdated(Long rowsUpdated) {
        this.rowsUpdated = rowsUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.update_latency
     *
     * @return the value of x$schema_index_statistics.update_latency
     *
     * @mbg.generated
     */
    public Long getUpdateLatency() {
        return updateLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.update_latency
     *
     * @param updateLatency the value for x$schema_index_statistics.update_latency
     *
     * @mbg.generated
     */
    public void setUpdateLatency(Long updateLatency) {
        this.updateLatency = updateLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.rows_deleted
     *
     * @return the value of x$schema_index_statistics.rows_deleted
     *
     * @mbg.generated
     */
    public Long getRowsDeleted() {
        return rowsDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.rows_deleted
     *
     * @param rowsDeleted the value for x$schema_index_statistics.rows_deleted
     *
     * @mbg.generated
     */
    public void setRowsDeleted(Long rowsDeleted) {
        this.rowsDeleted = rowsDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$schema_index_statistics.delete_latency
     *
     * @return the value of x$schema_index_statistics.delete_latency
     *
     * @mbg.generated
     */
    public Long getDeleteLatency() {
        return deleteLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$schema_index_statistics.delete_latency
     *
     * @param deleteLatency the value for x$schema_index_statistics.delete_latency
     *
     * @mbg.generated
     */
    public void setDeleteLatency(Long deleteLatency) {
        this.deleteLatency = deleteLatency;
    }
}