package test.model;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table x$user_summary
 */
public class XUserSummary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.statements
     *
     * @mbg.generated
     */
    private BigDecimal statements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.statement_latency
     *
     * @mbg.generated
     */
    private BigDecimal statementLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.statement_avg_latency
     *
     * @mbg.generated
     */
    private BigDecimal statementAvgLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.table_scans
     *
     * @mbg.generated
     */
    private BigDecimal tableScans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.file_ios
     *
     * @mbg.generated
     */
    private BigDecimal fileIos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.file_io_latency
     *
     * @mbg.generated
     */
    private BigDecimal fileIoLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.current_connections
     *
     * @mbg.generated
     */
    private BigDecimal currentConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.total_connections
     *
     * @mbg.generated
     */
    private BigDecimal totalConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.unique_hosts
     *
     * @mbg.generated
     */
    private Long uniqueHosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.current_memory
     *
     * @mbg.generated
     */
    private BigDecimal currentMemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$user_summary.total_memory_allocated
     *
     * @mbg.generated
     */
    private BigDecimal totalMemoryAllocated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.user
     *
     * @return the value of x$user_summary.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.user
     *
     * @param user the value for x$user_summary.user
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.statements
     *
     * @return the value of x$user_summary.statements
     *
     * @mbg.generated
     */
    public BigDecimal getStatements() {
        return statements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.statements
     *
     * @param statements the value for x$user_summary.statements
     *
     * @mbg.generated
     */
    public void setStatements(BigDecimal statements) {
        this.statements = statements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.statement_latency
     *
     * @return the value of x$user_summary.statement_latency
     *
     * @mbg.generated
     */
    public BigDecimal getStatementLatency() {
        return statementLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.statement_latency
     *
     * @param statementLatency the value for x$user_summary.statement_latency
     *
     * @mbg.generated
     */
    public void setStatementLatency(BigDecimal statementLatency) {
        this.statementLatency = statementLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.statement_avg_latency
     *
     * @return the value of x$user_summary.statement_avg_latency
     *
     * @mbg.generated
     */
    public BigDecimal getStatementAvgLatency() {
        return statementAvgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.statement_avg_latency
     *
     * @param statementAvgLatency the value for x$user_summary.statement_avg_latency
     *
     * @mbg.generated
     */
    public void setStatementAvgLatency(BigDecimal statementAvgLatency) {
        this.statementAvgLatency = statementAvgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.table_scans
     *
     * @return the value of x$user_summary.table_scans
     *
     * @mbg.generated
     */
    public BigDecimal getTableScans() {
        return tableScans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.table_scans
     *
     * @param tableScans the value for x$user_summary.table_scans
     *
     * @mbg.generated
     */
    public void setTableScans(BigDecimal tableScans) {
        this.tableScans = tableScans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.file_ios
     *
     * @return the value of x$user_summary.file_ios
     *
     * @mbg.generated
     */
    public BigDecimal getFileIos() {
        return fileIos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.file_ios
     *
     * @param fileIos the value for x$user_summary.file_ios
     *
     * @mbg.generated
     */
    public void setFileIos(BigDecimal fileIos) {
        this.fileIos = fileIos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.file_io_latency
     *
     * @return the value of x$user_summary.file_io_latency
     *
     * @mbg.generated
     */
    public BigDecimal getFileIoLatency() {
        return fileIoLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.file_io_latency
     *
     * @param fileIoLatency the value for x$user_summary.file_io_latency
     *
     * @mbg.generated
     */
    public void setFileIoLatency(BigDecimal fileIoLatency) {
        this.fileIoLatency = fileIoLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.current_connections
     *
     * @return the value of x$user_summary.current_connections
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentConnections() {
        return currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.current_connections
     *
     * @param currentConnections the value for x$user_summary.current_connections
     *
     * @mbg.generated
     */
    public void setCurrentConnections(BigDecimal currentConnections) {
        this.currentConnections = currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.total_connections
     *
     * @return the value of x$user_summary.total_connections
     *
     * @mbg.generated
     */
    public BigDecimal getTotalConnections() {
        return totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.total_connections
     *
     * @param totalConnections the value for x$user_summary.total_connections
     *
     * @mbg.generated
     */
    public void setTotalConnections(BigDecimal totalConnections) {
        this.totalConnections = totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.unique_hosts
     *
     * @return the value of x$user_summary.unique_hosts
     *
     * @mbg.generated
     */
    public Long getUniqueHosts() {
        return uniqueHosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.unique_hosts
     *
     * @param uniqueHosts the value for x$user_summary.unique_hosts
     *
     * @mbg.generated
     */
    public void setUniqueHosts(Long uniqueHosts) {
        this.uniqueHosts = uniqueHosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.current_memory
     *
     * @return the value of x$user_summary.current_memory
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentMemory() {
        return currentMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.current_memory
     *
     * @param currentMemory the value for x$user_summary.current_memory
     *
     * @mbg.generated
     */
    public void setCurrentMemory(BigDecimal currentMemory) {
        this.currentMemory = currentMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$user_summary.total_memory_allocated
     *
     * @return the value of x$user_summary.total_memory_allocated
     *
     * @mbg.generated
     */
    public BigDecimal getTotalMemoryAllocated() {
        return totalMemoryAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$user_summary.total_memory_allocated
     *
     * @param totalMemoryAllocated the value for x$user_summary.total_memory_allocated
     *
     * @mbg.generated
     */
    public void setTotalMemoryAllocated(BigDecimal totalMemoryAllocated) {
        this.totalMemoryAllocated = totalMemoryAllocated;
    }
}