package test.model;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table x$waits_by_host_by_latency
 */
public class XWaitsByHostByLatency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$waits_by_host_by_latency.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$waits_by_host_by_latency.event
     *
     * @mbg.generated
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$waits_by_host_by_latency.total
     *
     * @mbg.generated
     */
    private Long total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$waits_by_host_by_latency.total_latency
     *
     * @mbg.generated
     */
    private Long totalLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$waits_by_host_by_latency.avg_latency
     *
     * @mbg.generated
     */
    private Long avgLatency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x$waits_by_host_by_latency.max_latency
     *
     * @mbg.generated
     */
    private Long maxLatency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$waits_by_host_by_latency.host
     *
     * @return the value of x$waits_by_host_by_latency.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$waits_by_host_by_latency.host
     *
     * @param host the value for x$waits_by_host_by_latency.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$waits_by_host_by_latency.event
     *
     * @return the value of x$waits_by_host_by_latency.event
     *
     * @mbg.generated
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$waits_by_host_by_latency.event
     *
     * @param event the value for x$waits_by_host_by_latency.event
     *
     * @mbg.generated
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$waits_by_host_by_latency.total
     *
     * @return the value of x$waits_by_host_by_latency.total
     *
     * @mbg.generated
     */
    public Long getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$waits_by_host_by_latency.total
     *
     * @param total the value for x$waits_by_host_by_latency.total
     *
     * @mbg.generated
     */
    public void setTotal(Long total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$waits_by_host_by_latency.total_latency
     *
     * @return the value of x$waits_by_host_by_latency.total_latency
     *
     * @mbg.generated
     */
    public Long getTotalLatency() {
        return totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$waits_by_host_by_latency.total_latency
     *
     * @param totalLatency the value for x$waits_by_host_by_latency.total_latency
     *
     * @mbg.generated
     */
    public void setTotalLatency(Long totalLatency) {
        this.totalLatency = totalLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$waits_by_host_by_latency.avg_latency
     *
     * @return the value of x$waits_by_host_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public Long getAvgLatency() {
        return avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$waits_by_host_by_latency.avg_latency
     *
     * @param avgLatency the value for x$waits_by_host_by_latency.avg_latency
     *
     * @mbg.generated
     */
    public void setAvgLatency(Long avgLatency) {
        this.avgLatency = avgLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x$waits_by_host_by_latency.max_latency
     *
     * @return the value of x$waits_by_host_by_latency.max_latency
     *
     * @mbg.generated
     */
    public Long getMaxLatency() {
        return maxLatency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x$waits_by_host_by_latency.max_latency
     *
     * @param maxLatency the value for x$waits_by_host_by_latency.max_latency
     *
     * @mbg.generated
     */
    public void setMaxLatency(Long maxLatency) {
        this.maxLatency = maxLatency;
    }
}