package test.dao;

import java.util.List;
import test.model.DataLockWaits;

public interface DataLockWaitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lock_waits
     *
     * @mbg.generated
     */
    int insert(DataLockWaits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_lock_waits
     *
     * @mbg.generated
     */
    List<DataLockWaits> selectAll();
}