package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.DataLocks;

public interface DataLocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_locks
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("engineLockId") String engineLockId, @Param("engine") String engine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_locks
     *
     * @mbg.generated
     */
    int insert(DataLocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_locks
     *
     * @mbg.generated
     */
    DataLocks selectByPrimaryKey(@Param("engineLockId") String engineLockId, @Param("engine") String engine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_locks
     *
     * @mbg.generated
     */
    List<DataLocks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_locks
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataLocks record);
}