package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.EventsStatementsSummaryByThreadByEventName;

public interface EventsStatementsSummaryByThreadByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("threadId") Long threadId, @Param("eventName") String eventName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    int insert(EventsStatementsSummaryByThreadByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    EventsStatementsSummaryByThreadByEventName selectByPrimaryKey(@Param("threadId") Long threadId, @Param("eventName") String eventName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    List<EventsStatementsSummaryByThreadByEventName> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventsStatementsSummaryByThreadByEventName record);
}