package test.dao;

import java.util.List;
import test.model.EventsErrorsSummaryGlobalByError;

public interface EventsErrorsSummaryGlobalByErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_errors_summary_global_by_error
     *
     * @mbg.generated
     */
    int insert(EventsErrorsSummaryGlobalByError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_errors_summary_global_by_error
     *
     * @mbg.generated
     */
    List<EventsErrorsSummaryGlobalByError> selectAll();
}