package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.EventsWaitsSummaryByThreadByEventName;

public interface EventsWaitsSummaryByThreadByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("threadId") Long threadId, @Param("eventName") String eventName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    int insert(EventsWaitsSummaryByThreadByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    EventsWaitsSummaryByThreadByEventName selectByPrimaryKey(@Param("threadId") Long threadId, @Param("eventName") String eventName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    List<EventsWaitsSummaryByThreadByEventName> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_thread_by_event_name
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventsWaitsSummaryByThreadByEventName record);
}