package test.dao;

import java.util.List;
import test.model.EventsErrorsSummaryByThreadByError;

public interface EventsErrorsSummaryByThreadByErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_errors_summary_by_thread_by_error
     *
     * @mbg.generated
     */
    int insert(EventsErrorsSummaryByThreadByError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_errors_summary_by_thread_by_error
     *
     * @mbg.generated
     */
    List<EventsErrorsSummaryByThreadByError> selectAll();
}