package test.dao;

import java.util.List;
import test.model.EventsWaitsSummaryByUserByEventName;

public interface EventsWaitsSummaryByUserByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_user_by_event_name
     *
     * @mbg.generated
     */
    int insert(EventsWaitsSummaryByUserByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_user_by_event_name
     *
     * @mbg.generated
     */
    List<EventsWaitsSummaryByUserByEventName> selectAll();
}