package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.EventsTransactionsCurrent;

public interface EventsTransactionsCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_current
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("threadId") Long threadId, @Param("eventId") Long eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_current
     *
     * @mbg.generated
     */
    int insert(EventsTransactionsCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_current
     *
     * @mbg.generated
     */
    EventsTransactionsCurrent selectByPrimaryKey(@Param("threadId") Long threadId, @Param("eventId") Long eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_current
     *
     * @mbg.generated
     */
    List<EventsTransactionsCurrent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_current
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventsTransactionsCurrent record);
}