package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.EventsStatementsSummaryByProgram;

public interface EventsStatementsSummaryByProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_program
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("objectType") String objectType, @Param("objectSchema") String objectSchema, @Param("objectName") String objectName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_program
     *
     * @mbg.generated
     */
    int insert(EventsStatementsSummaryByProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_program
     *
     * @mbg.generated
     */
    EventsStatementsSummaryByProgram selectByPrimaryKey(@Param("objectType") String objectType, @Param("objectSchema") String objectSchema, @Param("objectName") String objectName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_program
     *
     * @mbg.generated
     */
    List<EventsStatementsSummaryByProgram> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_summary_by_program
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventsStatementsSummaryByProgram record);
}