package test.dao;

import java.util.List;
import test.model.EventsStatementsHistoryLong;

public interface EventsStatementsHistoryLongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated
     */
    int insert(EventsStatementsHistoryLong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history_long
     *
     * @mbg.generated
     */
    List<EventsStatementsHistoryLong> selectAll();
}