package test.dao;

import java.util.List;
import test.model.EventsWaitsSummaryByHostByEventName;

public interface EventsWaitsSummaryByHostByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_host_by_event_name
     *
     * @mbg.generated
     */
    int insert(EventsWaitsSummaryByHostByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_summary_by_host_by_event_name
     *
     * @mbg.generated
     */
    List<EventsWaitsSummaryByHostByEventName> selectAll();
}