package test.dao;

import java.util.List;
import test.model.HostSummaryByFileIoType;

public interface HostSummaryByFileIoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io_type
     *
     * @mbg.generated
     */
    int insert(HostSummaryByFileIoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io_type
     *
     * @mbg.generated
     */
    List<HostSummaryByFileIoType> selectAll();
}