package test.dao;

import java.util.List;
import test.model.InnodbTables;

public interface InnodbTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TABLES
     *
     * @mbg.generated
     */
    int insert(InnodbTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TABLES
     *
     * @mbg.generated
     */
    List<InnodbTables> selectAll();
}