package test.dao;

import java.util.List;
import test.model.InnodbBufferPageLru;

public interface InnodbBufferPageLruMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_PAGE_LRU
     *
     * @mbg.generated
     */
    int insert(InnodbBufferPageLru record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_PAGE_LRU
     *
     * @mbg.generated
     */
    List<InnodbBufferPageLru> selectAll();
}