package test.dao;

import java.util.List;
import test.model.InnodbBufferPage;

public interface InnodbBufferPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_PAGE
     *
     * @mbg.generated
     */
    int insert(InnodbBufferPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_PAGE
     *
     * @mbg.generated
     */
    List<InnodbBufferPage> selectAll();
}