package test.dao;

import java.util.List;
import test.model.InnodbTablespacesBrief;

public interface InnodbTablespacesBriefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TABLESPACES_BRIEF
     *
     * @mbg.generated
     */
    int insert(InnodbTablespacesBrief record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TABLESPACES_BRIEF
     *
     * @mbg.generated
     */
    List<InnodbTablespacesBrief> selectAll();
}