package test.dao;

import java.util.List;
import test.model.InnodbCmpmemReset;

public interface InnodbCmpmemResetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated
     */
    int insert(InnodbCmpmemReset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated
     */
    List<InnodbCmpmemReset> selectAll();
}