package test.dao;

import java.util.List;
import test.model.InnodbCmpmem;

public interface InnodbCmpmemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM
     *
     * @mbg.generated
     */
    int insert(InnodbCmpmem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM
     *
     * @mbg.generated
     */
    List<InnodbCmpmem> selectAll();
}