package test.dao;

import java.util.List;
import test.model.InnodbCmpReset;

public interface InnodbCmpResetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_RESET
     *
     * @mbg.generated
     */
    int insert(InnodbCmpReset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_RESET
     *
     * @mbg.generated
     */
    List<InnodbCmpReset> selectAll();
}