package test.dao;

import java.util.List;
import test.model.InnodbFtIndexTable;

public interface InnodbFtIndexTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_TABLE
     *
     * @mbg.generated
     */
    int insert(InnodbFtIndexTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_TABLE
     *
     * @mbg.generated
     */
    List<InnodbFtIndexTable> selectAll();
}