package test.dao;

import java.util.List;
import test.model.InnodbColumns;

public interface InnodbColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_COLUMNS
     *
     * @mbg.generated
     */
    int insert(InnodbColumns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_COLUMNS
     *
     * @mbg.generated
     */
    List<InnodbColumns> selectAll();
}