package test.dao;

import java.util.List;
import test.model.LogStatus;

public interface LogStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_status
     *
     * @mbg.generated
     */
    int insert(LogStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_status
     *
     * @mbg.generated
     */
    List<LogStatus> selectAll();
}