package test.dao;

import java.util.List;
import test.model.MutexInstances;

public interface MutexInstancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutex_instances
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long objectInstanceBegin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutex_instances
     *
     * @mbg.generated
     */
    int insert(MutexInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutex_instances
     *
     * @mbg.generated
     */
    MutexInstances selectByPrimaryKey(Long objectInstanceBegin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutex_instances
     *
     * @mbg.generated
     */
    List<MutexInstances> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mutex_instances
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MutexInstances record);
}