package test.dao;

import java.util.List;
import test.model.Parameters;

public interface ParametersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated
     */
    int insert(Parameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated
     */
    List<Parameters> selectAll();
}