package test.dao;

import java.util.List;
import test.model.PersistedVariables;

public interface PersistedVariablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persisted_variables
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persisted_variables
     *
     * @mbg.generated
     */
    int insert(PersistedVariables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persisted_variables
     *
     * @mbg.generated
     */
    PersistedVariables selectByPrimaryKey(String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persisted_variables
     *
     * @mbg.generated
     */
    List<PersistedVariables> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persisted_variables
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PersistedVariables record);
}