package test.dao;

import java.util.List;
import test.model.Processlist;

public interface ProcesslistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processlist
     *
     * @mbg.generated
     */
    int insert(Processlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processlist
     *
     * @mbg.generated
     */
    List<Processlist> selectAll();
}