package test.dao;

import java.util.List;
import test.model.ReplicationGroupMemberStats;

public interface ReplicationGroupMemberStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated
     */
    int insert(ReplicationGroupMemberStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated
     */
    List<ReplicationGroupMemberStats> selectAll();
}