package test.dao;

import java.util.List;
import test.model.ResourceGroups;

public interface ResourceGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE_GROUPS
     *
     * @mbg.generated
     */
    int insert(ResourceGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE_GROUPS
     *
     * @mbg.generated
     */
    List<ResourceGroups> selectAll();
}