package test.dao;

import java.util.List;
import test.model.ServerCost;

public interface ServerCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String costName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated
     */
    int insert(ServerCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated
     */
    ServerCost selectByPrimaryKey(String costName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated
     */
    List<ServerCost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServerCost record);
}