package test.dao;

import java.util.List;
import test.model.SessionStatus;

public interface SessionStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_status
     *
     * @mbg.generated
     */
    int insert(SessionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_status
     *
     * @mbg.generated
     */
    SessionStatus selectByPrimaryKey(String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_status
     *
     * @mbg.generated
     */
    List<SessionStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SessionStatus record);
}