package test.dao;

import java.util.List;
import test.model.SetupInstruments;

public interface SetupInstrumentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_instruments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_instruments
     *
     * @mbg.generated
     */
    int insert(SetupInstruments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_instruments
     *
     * @mbg.generated
     */
    SetupInstruments selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_instruments
     *
     * @mbg.generated
     */
    List<SetupInstruments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_instruments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SetupInstruments record);
}