package test.dao;

import java.util.List;
import test.model.SetupObjects;

public interface SetupObjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_objects
     *
     * @mbg.generated
     */
    int insert(SetupObjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_objects
     *
     * @mbg.generated
     */
    List<SetupObjects> selectAll();
}