package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.SlaveWorkerInfo;

public interface SlaveWorkerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("channelName") String channelName, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated
     */
    int insert(SlaveWorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated
     */
    SlaveWorkerInfo selectByPrimaryKey(@Param("channelName") String channelName, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated
     */
    List<SlaveWorkerInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlaveWorkerInfo record);
}