package test.dao;

import java.util.List;
import test.model.StatementsWithRuntimesIn95thPercentile;

public interface StatementsWithRuntimesIn95thPercentileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated
     */
    int insert(StatementsWithRuntimesIn95thPercentile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated
     */
    List<StatementsWithRuntimesIn95thPercentile> selectAll();
}