package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.StatusByThread;

public interface StatusByThreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_by_thread
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("threadId") Long threadId, @Param("variableName") String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_by_thread
     *
     * @mbg.generated
     */
    int insert(StatusByThread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_by_thread
     *
     * @mbg.generated
     */
    StatusByThread selectByPrimaryKey(@Param("threadId") Long threadId, @Param("variableName") String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_by_thread
     *
     * @mbg.generated
     */
    List<StatusByThread> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_by_thread
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StatusByThread record);
}