package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.UserVariablesByThread;

public interface UserVariablesByThreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_variables_by_thread
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("threadId") Long threadId, @Param("variableName") String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_variables_by_thread
     *
     * @mbg.generated
     */
    int insert(UserVariablesByThread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_variables_by_thread
     *
     * @mbg.generated
     */
    UserVariablesByThread selectByPrimaryKey(@Param("threadId") Long threadId, @Param("variableName") String variableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_variables_by_thread
     *
     * @mbg.generated
     */
    List<UserVariablesByThread> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_variables_by_thread
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserVariablesByThread record);
}