package test.dao;

import java.util.List;
import test.model.Views;

public interface ViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated
     */
    int insert(Views record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated
     */
    List<Views> selectAll();
}