package test.dao;

import java.util.List;
import test.model.ViewTableUsage;

public interface ViewTableUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_TABLE_USAGE
     *
     * @mbg.generated
     */
    int insert(ViewTableUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEW_TABLE_USAGE
     *
     * @mbg.generated
     */
    List<ViewTableUsage> selectAll();
}