package test.dao;

import java.util.List;
import test.model.XHostSummaryByStatementType;

public interface XHostSummaryByStatementTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_type
     *
     * @mbg.generated
     */
    int insert(XHostSummaryByStatementType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_type
     *
     * @mbg.generated
     */
    List<XHostSummaryByStatementType> selectAll();
}