package test.dao;

import java.util.List;
import test.model.XHostSummaryByStatementLatency;

public interface XHostSummaryByStatementLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated
     */
    int insert(XHostSummaryByStatementLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated
     */
    List<XHostSummaryByStatementLatency> selectAll();
}