package test.dao;

import java.util.List;
import test.model.XInnodbBufferStatsByTable;

public interface XInnodbBufferStatsByTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated
     */
    int insert(XInnodbBufferStatsByTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated
     */
    List<XInnodbBufferStatsByTable> selectAll();
}