package test.dao;

import java.util.List;
import test.model.XInnodbBufferStatsBySchema;

public interface XInnodbBufferStatsBySchemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated
     */
    int insert(XInnodbBufferStatsBySchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated
     */
    List<XInnodbBufferStatsBySchema> selectAll();
}