package test.dao;

import java.util.List;
import test.model.XIoByThreadByLatency;

public interface XIoByThreadByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_by_thread_by_latency
     *
     * @mbg.generated
     */
    int insert(XIoByThreadByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_by_thread_by_latency
     *
     * @mbg.generated
     */
    List<XIoByThreadByLatency> selectAll();
}