package test.dao;

import java.util.List;
import test.model.XIoGlobalByWaitByLatency;

public interface XIoGlobalByWaitByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_wait_by_latency
     *
     * @mbg.generated
     */
    int insert(XIoGlobalByWaitByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_wait_by_latency
     *
     * @mbg.generated
     */
    List<XIoGlobalByWaitByLatency> selectAll();
}