package test.dao;

import java.util.List;
import test.model.XLatestFileIo;

public interface XLatestFileIoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$latest_file_io
     *
     * @mbg.generated
     */
    int insert(XLatestFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$latest_file_io
     *
     * @mbg.generated
     */
    List<XLatestFileIo> selectAll();
}