package test.dao;

import java.util.List;
import test.model.XSchemaTablesWithFullTableScans;

public interface XSchemaTablesWithFullTableScansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated
     */
    int insert(XSchemaTablesWithFullTableScans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated
     */
    List<XSchemaTablesWithFullTableScans> selectAll();
}