package test.dao;

import java.util.List;
import test.model.XStatementsWithTempTables;

public interface XStatementsWithTempTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated
     */
    int insert(XStatementsWithTempTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated
     */
    List<XStatementsWithTempTables> selectAll();
}