package test.dao;

import java.util.List;
import test.model.XUserSummaryByFileIoType;

public interface XUserSummaryByFileIoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io_type
     *
     * @mbg.generated
     */
    int insert(XUserSummaryByFileIoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io_type
     *
     * @mbg.generated
     */
    List<XUserSummaryByFileIoType> selectAll();
}