package test.dao;

import java.util.List;
import test.model.XWaitsByHostByLatency;

public interface XWaitsByHostByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_host_by_latency
     *
     * @mbg.generated
     */
    int insert(XWaitsByHostByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_host_by_latency
     *
     * @mbg.generated
     */
    List<XWaitsByHostByLatency> selectAll();
}