package test.dao;

import java.util.List;
import test.model.XWaitsGlobalByLatency;

public interface XWaitsGlobalByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_global_by_latency
     *
     * @mbg.generated
     */
    int insert(XWaitsGlobalByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_global_by_latency
     *
     * @mbg.generated
     */
    List<XWaitsGlobalByLatency> selectAll();
}