package test.dao;

import java.util.List;
import test.model.XWaitsByUserByLatency;

public interface XWaitsByUserByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated
     */
    int insert(XWaitsByUserByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated
     */
    List<XWaitsByUserByLatency> selectAll();
}